### ISSUE TITLE
[第5回] 会場情報

### ISSUE THREAD

**Issue by BBCapMegane** [teckup-tokyo/LT#100]
### 場所
  - 住所
  -  最寄り

### 入退館情報
  - 入場方法
  - 退館方法

### 設備情報
  - 変換ケーブル (種類)
  - プロジェクター(ある？ない？)
  - マイク(ある？ない？)
  - フリーWi-Fi (ある？ない？)
  - 電源ケーブル (ある？ない？)

**Comment by tamanobi** [comment]
# 場所
- 最寄り: 北参道駅、次点で千駄ヶ谷駅・代々木駅
- 住所: 〒151-0051 東京都渋谷区千駄ケ谷４丁目２３−５ ＪＰＲ千駄ヶ谷ビル 6F

# 入退館情報
- 入場方法: 係員の指示で裏口から
- 退場方法: 係員の指示で裏口から

# 設備情報
- 変換テーブル（種類）: Type-C, HDMI
- プロジェクターある（2面）
- マイクある
- フリーWi-Fiある
- 電源ケーブル（一部）
