### ISSUE TITLE
[第5回] 懇親会のお金について

### ISSUE THREAD

**Issue by BBCapMegane** [teckup-tokyo/LT#103]
懇親会のお金について検討

参加者からお1人 500円徴収して、足が出たら運営が負担

**Comment by BBCapMegane** [comment]
[fix]
参加者からお一人 500円ほど徴収して、足が出たら運営が負担てきなので行こうかなー思いますがどうですか？

**Comment by tamanobi** [comment]
良さそう。

**Comment by yutonihei** [comment]
それでいいとおもいますー！

**Comment by BBCapMegane** [comment]
>参加者からお一人 500円ほど徴収して、足が出たら運営が負担てきなので行こうかなー思いますがどうですか？

賛成多数により、fix とさせていただきます
