### ISSUE TITLE
【第5回】 振り返り

### ISSUE THREAD

**Issue by yumechi** [teckup-tokyo/LT#106]
* 振り返りを書く
* 可能なら直接集合で振り返り
* 調整さん https://chouseisan.com/s?h=3dfc6887276348b78dd718e02b1cb7cb

----
以下、山際のメモ

# 振り返りでやること
- 各個人のY, W, Tを聞く(20min)
- すぐに改善できそうなもの、すぐに改善できなさそうなもの（議論が必要だったり）に分ける（10min）
- 分けたものを期限付きで、担当者を決める。期限は短めで
  - 実行しづらいものは、ドキュメントに起こすとか、考えをメモにまとめるなどの中間成果物を置く
  - 成果物がないものがないように配慮する（XXXに聞くなどのタスクは、聞いたことをまとめるようにして成果を見える化する）
- 感想戦もやりたい（30min）

# 今後、 TeckUp に求めることを聞いてみる（30min）
- 各個人に TeckUp に求めることを聞いてみたい
- その上で、 TeckUp がどうなっていったらいいのか考えてみたい

**Comment by yumechi** [comment]
# Y
* 様々な人に声をかけてみた
* 色々宣伝を考えた（メール、DM、etc...）
* イベント中の進行で色々フォロー？っぽいことをした

# W
* 意外と来ることがある
* 会場の人を巻き込めるととても良い
* 各種ツールの認識がズレてそう
* コミュニケーションの場所をなんとか誘導したいと思った
* 飛び込み枠用意したら色んな人が話した。とても良かった。

# T
* 飛び込み枠の継続
* 各種ツール、サービスの使い方、運用フローを整備
* アンケートを一度Googleフォームに、は改善したい
* 新規スタッフを増やしたい（慣れてしまってメタ知識に頼ってる部分があると感じてきた）
* 宣伝方法を戦略的にやりたい（今回個人の力によるものがやや強かったような）
* やるだけ、からのステップアップとしてKPIとかそろそろ考えたい
* 人を呼び込む施策としてテーマをもう少し詰めるとか、宣伝の仕方を変える。友達にまず来てもらうことが大事。そういう意味で周りにいるエンジニアが来たくなるような企画を考える。

**Comment by tamanobi** [comment]
Y

会場提供した
会場準備をした
会場LTをした
会社とオンラインサロンでLT会の宣伝をした
TeckUp二次会に参加した
令和というテーマについてヒアリングした

W

会場出入りするカードキーは複数あったほうが便利だが、１つあれば問題にならない
お酒はそこそこな量を余らせる
参加者の名札が欲しい
会場前で入場案内するときはスタッフだとわかる表示があると良い
懇親会は会場内での短時間だけで開始することができた
懇親会は締めないといつまでも終わらない
スプレッドシートに質問を書くスタイルは質問しづらかった
質問方法やLT会の案内が当日に決まっており、良い風潮とは思えない
人と話すタイミングがわからない上、話づらかった
令和というテーマは考えづらかったという声を3名からもらった

T

カードキーは１つでいい
お酒の調達をもっと少なくする。多くて一人二本くらい
スタッフはスタッフだとわかる、名札を作り、かけてもらう
発表者には名札を作り、当日渡す
懇親会の終了日時を目立つ場所に、書いておく（ディスプレイでもいい）
懇親会をやる場合は、場所を近くし丁寧に誘導する
質問の方法は挙手制とSli.doを両方使う。Sli.doはどこかのディスプレイに出しておく
当日の進行についてドキュメントを用意して、誰でもできるようにしておく
所属しているコミュニティへの宣伝を続ける
TeckUpの存在理由についてスタッフの中で共有する

**Comment by yutonihei** [comment]
## Y
* 懇親会用ドリンク・フード・雑品の見積・発注
* 会場外から会場までの案内
* iPad提供（タイマー用）
* 懇親会参加
## W
* 質問が後半になるにつれ少なくなっていた気がする。
* 質問が共有されないGoogleフォーム方式だとどんな質問が挙がったのか参加者として認識しにくいと感じた。
* 喋ろうとした際に名前が分からない事態が発生するため、名札は欲しいと感じた。
* 同じく、スタッフ用の名札も欲しい気がした。
* 会場の撮影、参加者への撮影の許可などの周知について曖昧だった気がした（後々ブログとか書く材料にしたい）
* iPadでのLTの時間管理悪くなかったと思う。懸念事項としてはiPad所持者が居なかった場合の代替手段は持ってた方が良いと感じた。
* 案内は2人で良かったが、会場までの案内用のカードは1枚で充分だった。（一人が下で参加者を待機させ、一人がピストンする形式は結構よかった）
* 懇親会が同会場だったためスムーズに移行する事ができた。
* 当日無断キャンセルなどが発生し、懇親会用のドリンクが過剰に余ってしまった。ただ想定していた1人2本ベースという読み自体は大体当たっていたのでよかった。
* 飲食物が余った際にどうするかを決めてなかったため、スタッフ全員に確認する必要があった。
* フードに関して不足していた。ピザの注文以外にお菓子類がもっとあっても良かった。
* ソフトドリンクについては炭酸飲料は不要？ソフドリ2本お茶1本でもよい気がした。
* 直前に調達したため、もっと安く調達できる方法があると感じた。
* 総じて、一人500円だと赤字ベースになる事がわかった。
* 懇親会の終了が曖昧な終わり方で一部参加者が帰りにくい雰囲気を作ってしまったと思っている。
## T
* 懇親会参加＆当日無断キャンセルの対策の検討
* スタッフ用・参加者用名札の検討

**Comment by nmeguro** [comment]
#### Y -やったこと

- 当日の司会

#### W - わかったこと

- もろもろ準備と確認が不足している
  - 質問フォームのURL間違い
  - 会場説明を後からする
  - SlackのURL共有しちゃう
  - 懇親会の終了時間を決めていない

- Googleフォームで質問もらうのやっぱりやりたくない
  - ダサいから。
  - Sli.do使うと時系列で追いにくいと思ったが、次回はやったら良いと思う。
  - 本当はTwitterで質問を拾いたいが、感想とごっちゃになってる＆ツイートしてる人少なさそう。

- 参加者が何者かもう少し知りたい（名刺もらうとか）

#### T - つぎやること

- ちゃんと準備する
  - もう司会2回目なんだからテンプレ作ればいいのに。
- Sil.do使ってみる

**Comment by BBCapMegane** [comment]
### Y
- Issue 切り
- 宣伝等
- connpass のイベント内容作成と反映
- 前日メール
- 担当の割り振りとか
- タスクの進捗管理

### W
- 担当割り振りは挙手制より、指名性がよい
- キックオフのとき、なにを決めたいかを考えてからやったのはよかった
- ピクシブさん最高
- 人は集めるのは大変
- LTはテーマは縛りがないほうが面白い
- 飛び込み枠はライブ性があってよい
- 名札は用意したほうがいい
- 自分がIssue切りしたけど、もうちょっと他の人にも提案してもらえるような環境にすべきだった
- 質問は挙手制のほうがよい

### T
- TeckUPの方向性の話
- 方向性を参加者に明確に伝える
- 集客について考える

**Comment by IkezoeMakoto** [comment]
## Y
* twitterした（色々な情報流したり）
* タイムキーパーしようとしたけど目黒さん（司会）がやってくれた
* 時間調整したりした（遅延、前倒しの管理）
* 興味ありそうな後輩を誘った

## W
* 人数さえ集まればだいたいなんとかなる
* 発表は割とみんなレベル高い
* 懇親会の流れスムーズでいい感じ
* 人集めるところは力かけてやらないと初動動かない
* 飲食の確認ちゃんとしないといけない
* アンケートフォームのQRミス
* 質問があまり盛り上がらなかった→可視化？
* アンケートの結果とかみんなが見れるところに一括管理したい
    * https://drive.google.com/drive/u/0/folders/1LdbCeVXjyjXpXcSvlmzH7t_67cWBTgko

**Comment by tamanobi** [comment]
TeckUp について話した内容は、こちらです。
https://docs.google.com/document/d/1wgN4bJLAmDzrSsEnMPZuKE_rx-UTOr3SLdeNuPMcXFQ/edit

次のようにやっていきます。調整さんとかはあとで出しますね。
1. 次のアクションについて話す会を年内開催
2. もし、つぎにLTをやるならLT振り返りをもとにタスクを決める会をキックオフ

https://teckup-tokyo.slack.com/archives/CH7689XSS/p1574426799009100
