### ISSUE TITLE
当日の役割ぎめ

### ISSUE THREAD

**Issue by yumechi** [teckup-tokyo/LT#16]
* タイムキーパー
* 司会
* 接続補助
* 受付

これくらい？

**Comment by nmeguro** [comment]
ぱっと思いついた役割とかのメモ。

#### タイムキーパー
- LT会のオープニングで「発表＋質疑応答で1人〇分」と発表者の持ち時間を明示して、参加者全員で認識合わせる。
  - これは司会がやればおｋ
- 発表者の目の前にカウントダウンするタイマー（PCかスマホで）を設置＆リセット等の操作を行う
  - 司会がやるより他の誰かがやった方がシームレスに出来て良いと思う

#### 司会
- 当日のタイムテーブルをしっかり把握する（把握しておかないとグダる恐れあり）
  - 誰もいないなら目黒がやってもいいよ

#### 接続補助
- LT会開始前の受付で、発表者がやってきたらPCの接続確認を行う
  - 受付以外の人なら誰でもおｋ

#### 受付
- 入口の前で待ち構えて、来た人の名前を聞く。
  - 出欠をconnpassでつけることが可能なのでそれを使うと良いかも
  - LT会開始後に駆けつける人が居る可能性があるので、司会とは別の人が良いと思われる。

**Comment by yumechi** [comment]
大体上げてもらったとおりだと思います。

sli.do とかやるならもう一人はほしいね。
あと時間によって役割ローテするのも面白いかなと思ってます（前半の司会、後半の司会、みたいな感じで）

**Comment by nmeguro** [comment]
> 時間によって役割ローテ

それ良さそうだね！ 検討しよう。

**Comment by yumechi** [comment]
これ片付けも考えないといけなくて @Ushinji は会場責任者として残るとして、@sanolabs とかに任せたい

**Comment by Ushinji** [comment]
来週なので、役割分担を確定しますか。

* 司会->目黒

* sli.do -> 宇山
* 接続補助 -> 宇山

* タイムキーパー

* 受付

司会は @nmeguro さん、お願いします！
sli.doは表示に関連するので、 @Ushinji  が担当します。あと、接続補助も合わせて行います。

あと、タイムキーパーと、受付ですね。

@yumechi さん、どちらかやりたい方をお願いします。

**Comment by yumechi** [comment]
僕が受付をやります

**Comment by yumechi** [comment]
ごめん、ちょっと当日ですが、微妙だなと思って僕が佐野さんに受付を依頼しました。
（これは早く付きそうでやってくれそうだなと思ったので）

佐野さんほんとありがとなのと、僕は僕で職務を全うしなくてすみませんという感じです。
とはいえ、全体見る役に徹する人がいたほうがいいかなというのは今回感じました。（結構今回トラブル時にうまい感じに動けたかなと思う）
