### ISSUE TITLE
sli.do 等を活用できないか？

### ISSUE THREAD

**Issue by yumechi** [teckup-tokyo/LT#17]

**Comment by nmeguro** [comment]
一度、誰か試しで使ってみては（他力本願

**Comment by Ushinji** [comment]
参加した勉強会で使っていたので、写真撮った。

見た感じ、以下の仕様かと思う。
- 投稿された質問の一覧表示
- 各質問へ「いいね」が押せる
- 「いいね」数が多い順に上から表示される

感想としては、
- シャイな人でも質問できそう
- 他の人が質問が確認できるので、そこから別の疑問に気づいたりできる
- スピーカー、聞き手含めて、後でどんな質問が行われたか確認できるそう？(仕様は知らん)

![image from ios 2](https://user-images.githubusercontent.com/24544727/47169187-cd8f8180-d33d-11e8-95a8-0effd43aa3f1.jpg)

使っても良いのではと思った。

**Comment by yumechi** [comment]
ありがとうございます。入れてみたいなという気持ちが高まりました。専属で一人置く必要があるかもしれないけど…。

管理してんだと色々運用考える必要があるなあと下記の記事を読んで思ったので、どっかで使ってみる会みたいな検討事項を上げる時間が欲しい気持ちになる。

少人数～大人数の勉強会には「sli.do」を！ - Qiita https://qiita.com/anbhts/items/2b762fd313bc4fd22f16

**Comment by nmeguro** [comment]
Qiita読んだけど下記が気になった。これどうなんでしょう？？＞使ったことある人

>アンケートは３問まで作成可。それ以上の場合は古い質問を消して作成が必要。予め準備しておきましょう。

**Comment by yumechi** [comment]
ああ、これ忘れてた。質問が消える前に次の質問行かないでみたいな話は出てたみたい。
なので、人気があるやつは順番を守りましょう的な人間的なポリシーが求められるかも。

でも使うか使わないか、で言ったら使ったほうがいいですね。

**Comment by yumechi** [comment]
@Ushinji がいい感じにやってくれると信じてClose

多分当日使います
