### ISSUE TITLE
アイスブレイク

### ISSUE THREAD

**Issue by yumechi** [teckup-tokyo/LT#18]
* 発表者に身内が多い問題はある（だいたい初めて人は4割くらい？）
* 参加する人には楽しんでもらいたい
* 早く打ち解けるためにはどうすればいいかちょっと施策考える

**Comment by yumechi** [comment]
サポーターズみたいに、自己紹介的な何かを一番最初にやるのもあり

**Comment by yumechi** [comment]
10分位でやりたいよね

**Comment by Ushinji** [comment]
アイスブレイクはいいと思う！

あと、発表の合間の参加者同士の交流の時間を結構取りたいなと思う。特に、発表者が多いので(15人)なので、適度に休憩・交流時間を置かないと、聞く側は辛いなぁーと思ってます。

カンファレンスばりに、本気で学びまくりな会なら、別かもしれませんが。

**Comment by yumechi** [comment]
カンファレンスみたいに受け身になりまくるような状況はやだなあと思っていて、交流する時間は重視したいですね。
時間は長めに取りたい。可能なら会場入って先になんかやれるような仕組みも入れておきたい。（勉強会とかだとPCの前でがたがたやってる人が多いけど、そういうのをしないような流れを考えたい）

**Comment by nmeguro** [comment]
アイスブレイク、サポーターズ的な最初に半ば強引に全員に自己紹介させるのはアリかなと思ってる！
あと私もカンファレンス的な受け身な状況はアレだなと思うので、

> 適度に休憩・交流時間を置かないと

と思うけど、どれくらいの頻度が良いのかな～っていうのは考えあぐねている。。

**Comment by yumechi** [comment]
適度な時間はわからんけど、全体的なところらしいタイムスケジュールで調整することにして、自己紹介のアイスブレイクはサポーターズ様のやり方を真似てみよう。

いしゅーくろーず。
