### ISSUE TITLE
会場の増枠検討

### ISSUE THREAD

**Issue by yumechi** [teckup-tokyo/LT#19]
現在30人だけど、会場のキャパが許すならもう少し多めの人数を聞く人枠で追加したいよね。

まだ1ヶ月あるし、もう少し参加者伸びるはず。

**Comment by Ushinji** [comment]
40人なら大丈夫かと。それ超えると、まぁ大変になるかも。

**Comment by yumechi** [comment]
5枠くらい聞く人伸ばしてみるかー

**Comment by Ushinji** [comment]
やりましょー

**Comment by yumechi** [comment]
11月にやります

**Comment by yumechi** [comment]
5名増やしたので作業完了。
https://kizokukai.connpass.com/event/102653/
