### ISSUE TITLE
当日スケジュールぎめ

### ISSUE THREAD

**Issue by yumechi** [teckup-tokyo/LT#29]
@Ushinji による仮案

```
LTの説明等・アイスブレイク(10分)
発表① LT 10分 × 3本 (30分)
歓談・休憩①(15分)
発表② LT 5分 × 3本 (15分)
歓談・休憩②(15分)
発表③ LT 10分 × 3本 (30分)
歓談・休憩③(15分)
発表④ LT 5分 × 3本 (15分)
歓談・休憩④(15分)
発表⑤ LT 10分 × 3本 (30分)
歓談・休憩⑤(15分)
締め・撤収
```

もう少し洗練する

**Comment by yumechi** [comment]
13:30開始でも良いくらいの発表量になってることに気がついたので、仮案で出しておく。

```
会場受付 13:30〜
LTの説明・アイスブレイク 14:00〜14:15(15分)
発表① LT 10分 × 3本 14:15〜14:45(30分)
歓談・休憩①14:45〜15:00(15分)
発表② LT 5分 × 3本 15:15〜15:30(15分)
歓談・休憩②15:30〜15:45(15分)
発表③ LT 10分 × 3本15:45〜16:15 (30分)
歓談・休憩③16:15〜16:30(15分)
発表④ LT 5分 × 3本16:45〜17:00 (15分)
歓談・休憩④17:00〜17:15(15分)
飛び込み LT 10分 × 3本17:15〜 17:45(30分)
締め・撤収17:45〜18:00(15分)
```

**Comment by yumechi** [comment]
# 考えてみて思ったこと

* 15分発表、15分休憩は流石に休憩し過ぎな気がする
     * 1ブロック4本にする？
* 最後が飛び込みありき
     * 各種イベントの宣伝コーナーでもいい
     * いっそのことアンカンファレンス形式で、これから貴族会でやりたいこと、コミュニティでやってみたいことを話すとかでもいい
* 撤収時間の見積もりがこれでいいのかわからん

**Comment by Ushinji** [comment]
ちな、懇親会の予約は、17:30からです。

**Comment by Ushinji** [comment]
なので、13:30スタートで、撤収が17:30までに終わるスケージュールを提案です

**Comment by yumechi** [comment]
こんな感じになった。

| 活動             | 開始  | 終了  | 間隔    |
| ---------------- | ----- | ----- | ------- |
| 受付開始         | 13:00 | 13:30 | 0:30:00 |
| LTの説明・アイスブレイク  | 13:30 | 13:45 | 0:15:00 |
| 発表①            | 13:45 | 14:25 | 0:40:00 |
| 歓談・休憩①       | 14:25 | 14:40 | 0:15:00 |
| 発表②            | 14:40 | 15:20 | 0:40:00 |
| 歓談・休憩②       | 15:20 | 15:35 | 0:15:00 |
| 発表③            | 15:35 | 16:15 | 0:40:00 |
| 歓談・休憩③       | 16:15 | 16:30 | 0:15:00 |
| 飛び込みLT・宣伝タイム | 16:30 | 17:00 | 0:30:00 |
| 締め・撤収         | 17:00 | 17:30 | 0:30:00 |

**Comment by Ushinji** [comment]
@yumechi 
忙しい中で考えてくれてありがと！

前回からの変更点は以下に感じました。認識あってますかね？
* 発表者の人数が減って12人になった
* 15分発表の後が、15分休憩が長い気がするので、1ブロック4本にした
* 最後に、飛び込みLT、宣伝コーナーを入れた

飛び込みLT、宣伝コーナーを入れるのは、自分も良いと思います！

疑問点については、
* 当日発表者の順番をクジで決める、という話でしたが、上の発表の10分、5分の内訳はどのようになりますか？

ぐらいですかね。

**Comment by Ushinji** [comment]
@yumechi 
内訳について、

LT発表時間：１０分が８人
LT発表時間：５分が４人

なので

| 活動             | １０分の人数(時間)  | ５分の人数(時間)  | 合計時間 |
| ---------------- | ----- | ----- |----- |
| 発表①        | ３人(30分) | １人(5分) | 35分 |
| 発表②        | ３人(30分) | １人(5分) | 35分 |
| 発表③        | ２人(20分) | ２人(10分) | 30分 |

以上を踏まえて、以下スケジュール変更。

変更点は、
* 各発表枠の時間が減る(5分ぐらい)
* なので、減った分を休憩へ追加

| 活動             | 開始  | 終了  | 間隔    |
| ---------------- | ----- | ----- | ------- |
| 受付開始         | 13:00 | 13:30 | 0:30:00 |
| LTの説明・アイスブレイク  | 13:30 | 13:45 | 0:15:00 |
| 発表①            | 13:45 | 14:20 | 0:35:00 |
| 歓談・休憩①       | 14:20 | 14:40 | 0:20:00 |
| 発表②            | 14:40 | 15:15 | 0:35:00 |
| 歓談・休憩②       | 15:15 | 15:35 | 0:20:00 |
| 発表③            | 15:35 | 16:05 | 0:30:00 |
| 歓談・休憩③       | 16:05 | 16:25 | 0:20:00 |
| 飛び込みLT・宣伝タイム | 16:25 | 17:00 | 0:35:00 |
| 締め・撤収         | 17:00 | 17:30 | 0:30:00 |

**Comment by yumechi** [comment]
@Ushinji 上の案使いますね！

**Comment by yumechi** [comment]
connpassに書きました！
