### ISSUE TITLE
当日会場に置く飲食物の用意

### ISSUE THREAD

**Issue by yumechi** [teckup-tokyo/LT#30]
* お菓子
* ジュース

飲酒可能なのか？は少し引っかかってる。
日本酒を嗜みながらLTをする会も過去には存在していたので、昼からといえど飲みながら気楽な気持ちで参加したい人もいるのではないか？

**Comment by yutonihei** [comment]
個人的には可だが用意はしませんでいいと思います。
ジュース・お菓子についても正直準備する必要はないかと。
前回お菓子置いてある場所が奥だったのもあるけど食べてるのが一部だった記憶がありますので。
私感ですが、運営側で用意する必要もないかと（飲食したいものは自分でどうぞの考え）。

**Comment by yumechi** [comment]
↑だいたいそうした
私見としては、みんなでワイワイするためには私費をある程度払っても満足度をあげたいですが。
せっかく参加していただいた人をもてなしたいので。（別にキャッシュバックとかそういうのも期待してないです）

メールはこれを出した。
というわけで Close

```
貴族会 LT参加者各位

なんと開催までもう一週間を切りました！
運営のyumechiです。


改めて、今週土曜日の午後は貴族LT大会#2 です！
お忘れないように予定をチェックしておいてくださいね。


1つだけ連絡です。

会場は飲食可能…とのことなので、飲食品の持ち込みは各自でお願いします。
お土産のお菓子、差し入れのジュース、歓迎です！
アルコールもオッケーとのことなので、家で眠っているお酒等あればぜひ…！
発表で緊張している方も、少しだけ
お酒を飲むとリラックスできるかも
しれませんね。


なお、スペースはアディッシュ様からお借りしているので、
決して汚したり飲み物を零したりしないよう、お願いします。

以上です。
いよいよ冬本番に近づき、肌寒い日も
増えてましたので、風邪にはお気をつけくださいませ。

当日、皆様にお会いできること、心よりお待ちしております！
```
