### ISSUE TITLE
[第3回] 19/03/02(土) 貴族LT会の開催準備

### ISSUE THREAD

**Issue by yumechi** [teckup-tokyo/LT#35]

**Comment by Ushinji** [comment]
全体の流れ(適宜追加)
- [x] 会場の決定
  - WILLGATEさん
- [x] 日程の決定
  - 19/03/02(土)
- [ ] Conpassページの作成
  - https://github.com/kizokukai/Kizokukai_LT/issues/36
- [ ] Conpassページの公開

**Comment by IkezoeMakoto** [comment]
## 会場情報
* 場所 渋谷南東急ビル2F 
    * https://www.google.com/maps/place/%E3%80%92150-0002+%E6%9D%B1%E4%BA%AC%E9%83%BD%E6%B8%8B%E8%B0%B7%E5%8C%BA%E6%B8%8B%E8%B0%B7%EF%BC%93%E4%B8%81%E7%9B%AE%EF%BC%91%EF%BC%92%E2%88%92%EF%BC%91%EF%BC%98+%E6%B8%8B%E8%B0%B7%E5%8D%97%E6%9D%B1%E6%80%A5%E3%83%93%E3%83%AB/@35.6562323,139.7038671,17z/data=!3m1!4b1!4m5!3m4!1s0x60188b5bf30f781b:0x53a4c6407606f400!8m2!3d35.6562323!4d139.7060558
* 定員 40人
* 飲食
    * 可 (提供はないです。持参＆片付けさえしてくれればOK)

**Comment by Ushinji** [comment]
プルリク運用でLT会準備を行うことになったので、クローズします。
