### ISSUE TITLE
会場候補を見つける

### ISSUE THREAD

**Issue by yumechi** [teckup-tokyo/LT#4]

**Comment by Ushinji** [comment]
佐野氏の尽力により、会場候補は確定しました。

![ios](https://user-images.githubusercontent.com/24544727/45951574-e9557f80-c03e-11e8-841e-33ed5a0c6248.png)

**Comment by pinkumohikan** [comment]
いつもの渋谷スクエアA or 渋谷ファーストプレイス 8Fなら僕も手配出来るので、また場所が必要になったら声かけて下さい〜

**Comment by yumechi** [comment]
とりあえず会場問題は解決ということで。問題があれば、reopenします。
