### ISSUE TITLE
LT会準備に向けたリポジトリ運用の方針について

### ISSUE THREAD

**Issue by Ushinji** [teckup-tokyo/LT#42]
## 内容
運用について。

例えば、アンケート項目を考えるとして
- issue「アンケート項目を考える」を作る
   - issue内でアンケート項目を何にするか議論->アンケート項目が決定
- プルリク「アンケート項目の決定」を作る
   - ｀preparation.md｀ の「アンケート項目決定」をDONEにする
   - 必要であれば「conpass.md」へ追記(なければなし)
   - レビュー後、masterへマージ
- issueをクローズ

の方が良いか？

つまりぞえさんの言った通り
> issueで課題を報告→課題について議論→結果物として反映するべきものがあればPR出す→レビュー→マージ→issueクローズ

のように「issueは課題を議論する場」、「プルリクはissueで決まった結果物として反映する場(なければやらなくてよい)」と目的によって分ける方が良い？ 

正直やってみて、基本的に成果物がない場合もあるからissueで議論の方が良いと思った。ただ、成果物は残しておきたいから、その場合はプルリクを使うべきだと思った。

## 検討事項

運用方針の決定。↑のやり方で良いか。修正点はないか。

**Comment by IkezoeMakoto** [comment]
基本的に上記で大丈夫です。

少しPRでの伝え方が悪かったかもしれませんが、

特定のやり方がダメ、良いという話ではなく、場面場面に合わせて最適な方法を模索していきたいですね。という内容のメッセージでした。

## 運用イメージ
* 基本的に成果物のイメージがすり合っているものであればそのままPR（ただし1PR1目的）

* 場合によってはやらないといけないことは決まってるものの、中身をどうするかまだ定まっていないものなどがあったりするので、それに関してはissueにて方針を議論してから、PRにするなりしたい
    * 場合によっては1issueから複数PRが切られて、マージされていくなどという使い方もあると思います

**Comment by Ushinji** [comment]
> 基本的に上記で大丈夫です。
> 少しPRでの伝え方が悪かったかもしれませんが、
> 特定のやり方がダメ、良いという話ではなく、場面場面に合わせて最適な方法を模索していきたいですね。という内容のメッセージでした。

Issueとプルリクを組み合わせた運用が初めてなので、やりながら皆さんの意見を聞きながら、都度ケースに応じた運用を考えていました。そういう意味で、ぞえさんの意見はありがたいです。

ぞえさんの補足の中であった「1つのissue/1つのPR => 1つの目的」 は意識していきましょう！
なので、各issue/PRの「議題(目的)」は記述するようにする。

**Comment by IkezoeMakoto** [comment]
これも別issueでいいけど、PRテンプレート作れるので、そこに

>各issue/PRの「議題(目的)」は記述するようにする。

的なの入れてもいいですね！

**Comment by IkezoeMakoto** [comment]
あー、これあれかテンプレート作るって別issueに立てたのでこっちは運用回ってきたしクローズしちゃいますね
