### ISSUE TITLE
[第3回] LT会の発表テーマの選定

### ISSUE THREAD

**Issue by Ushinji** [teckup-tokyo/LT#44]
## 目的
- 第3回 LT会の発表テーマを議論し、発表テーマを決定すること

## 参考：過去のLT会のテーマ
1. 今の自分と、”貴族”になりたい野望
2. 今年1年の振り返りと、”貴族”としての来年への野望

## メモ(所感)
3月開催で、4月が近いので

> 「もうすぐ4月新年度！ "貴族として"新年度に向けてチャレンジすること/現在していること！」

的な切り口は良いのではないかと考えているが、何か別の切り口など議論していきたい。

**Comment by yutonihei** [comment]
自分の貴族の定義を支えるものについて熱く語るのはいかがだろう
野望願望ばかりじゃなく、色々なバックを持ってる人がいるって相互認識もできるかと

**Comment by Ushinji** [comment]
> 自分の貴族の定義を支えるものについて熱く語るのはいかがだろう
> 野望願望ばかりじゃなく、色々なバックを持ってる人がいるって相互認識もできるかと

なるほど。違う切り口は良いすね！
一つ聞きたいのは、 `自分の貴族の定義を支えるもの` て例えば、どんな内容だろうか？

**Comment by Ushinji** [comment]
例えば、自分は「お金持ち」がなりたい貴族の姿と定義する、とする場合、。
じゃぁ、なんで「お金持ち」である状態であることを望んでいるのか。それを思うに至った経緯は。

みたいな話か。

**Comment by IkezoeMakoto** [comment]
他に案はないかな。

せっかくだからいろんなテーマ案を見てみたいところ、以下ブレスト

* 自分の貴族たる所以とか（これこれこういう経緯で自分は貴族）
* ここ一年で貴族としてレベルアップした話（成長をテーマに）
* やらかし貴族（失敗談）
* 貴族の日常（普段業務や、プライベートでどんなことをしているか）

**Comment by nmeguro** [comment]
zoeさんが挙げてくれた内容で良いかなと。
毎回、具体的なテーマが無いことがうまみかなと思っています。
強いて言えば3月開催なので、新生活とか何かそういう季節ネタっぽい雰囲気が入ると良いのかも？

**Comment by Ushinji** [comment]
テーマ決めるの難しいですねw

思ったのは、過去のものと違ったテーマにしたい気持ちあります。
> 1. 今の自分と、”貴族”になりたい野望
> 2. 今年1年の振り返りと、”貴族”としての来年への野望

なので、今挙がっているテーマから、過去のものと違うものを選抜すると、以下３つですかね。

```
1. 自分の貴族たる所以とか（これこれこういう経緯で自分は貴族/自分の貴族の定義を支えるもの）
2. やらかし貴族（失敗談）
3. 貴族の日常（普段業務や、プライベートでどんなことをしているか）
```

で、この中から多数決で決めましょう！どれでやっても、面白そうだし(笑)

という提案です。どうでしょうか？

**Comment by IkezoeMakoto** [comment]
アンケート取った

`3. 貴族の日常（普段業務や、プライベートでどんなことをしているか）`

これで
