### ISSUE TITLE
[第3回] 2/2までにconnpassを公開するぞ

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#45]
> 公開までに少なくとも以下の内容をFixする必要ありです。
> -  テーマ
> -  LT登壇者数
> -  タイムスケジュール
> -  開始、終了時間
> -  Conpassアンケート

connpassページはこちら

https://kizokukai.connpass.com/event/118681/preview/

**Comment by IkezoeMakoto** [comment]
テーマ決めは

https://github.com/kizokukai/Kizokukai_LT/issues/44

でやってくれてる

**Comment by IkezoeMakoto** [comment]
LT登壇者数を決める

**Comment by IkezoeMakoto** [comment]
会場情報も記載しないと

**Comment by IkezoeMakoto** [comment]
connpassではないけど、当日の司会とかも決めないとね。

**Comment by Ushinji** [comment]
2/1(金) 9:30 現在で、Conpass公開までに決める必要がある項目は、ざっと以下の通りと認識しています。

- [第3回] LT会の発表テーマの選定
 https://github.com/kizokukai/Kizokukai_LT/issues/44
- [第３回] Conpassページから参加申し込みする際のアンケート
 https://github.com/kizokukai/Kizokukai_LT/issues/58
- [第3回] 当日スケジュールについて考える
 https://github.com/kizokukai/Kizokukai_LT/issues/57

当日のスケジュールは最悪、公開後修正は可能なのですが。

**Comment by IkezoeMakoto** [comment]
現状整理あざます！

そうですねテーマ選定動かないと、、

**Comment by yumechi** [comment]
投稿されてない

**Comment by IkezoeMakoto** [comment]
明日朝に公開するのと、告知回しますね

**Comment by IkezoeMakoto** [comment]
公開した
