### ISSUE TITLE
[第3回] LT登壇者数を決める

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#46]
LT登壇者数を決める

_Originally posted by @IkezoeMakoto in https://github.com/kizokukai/Kizokukai_LT/issues/45#issuecomment-458453456_

**Comment by IkezoeMakoto** [comment]
これはどうやって決めようかね

**Comment by Ushinji** [comment]
議論の補足として、

## 前回の登壇人数と時間配分

- 人数：11人 + 5人ぐらい(飛び込みLT)
- 時間
  - 10分：7人
  - 5分：4人

| ＃ | 発表者 | タイトル | 時間 |
| ---: | --- | --- | --- |
| 1 | [yumechi](https://twitter.com/__yumechi) | この一年の登壇を通して | 5分 |
| 2 | [shinji.uyama](https://twitter.com/u_shinji0612) | 転職してからの１年間を振り返る | 10分 |
| 3 | [takanakahiko](https://twitter.com/takanakahiko) | 同人誌で食べたい | 5分 |
| 4 | [pinkumohikan](https://twitter.com/pinkumohikan) | なにか話します！！！１１ | 10分 |
| 5 | [Taku](https://twitter.com/arakawa_gios)| 今年の貴族になるための取り組みと来年の野望(仮) | 10分 |
| 6 | [t.oda](https://twitter.com/Tkahiro_Oda) | 飽き性でもプログラミングがしたい！ | 10分 |
| 7 | [さのし](https://twitter.com/sano_shoichi) | 起業して1年経ったので学んだことを語る | 10分 |
| 8 | [ak_hina](https://twitter.com/ak_hina) | 客先常駐SEだって貴族になっていいはずだ | 10分 |
| 9 | [Linus_MK(ライナス)](https://linus-mk.hatenablog.com/) | 今年の振り返りと、やってみた恐怖症の話 | 10分 |
| 10 | [ツッキー](https://twitter.com/rs_tukki) | 未定(テスト自動化の話とかやるかも……？) | 5分 |
| 11 | [Takahiro](https://twitter.com/3ebxooc8SWUsmO8) | 個人でVueを触ってみた所感を話そうかなと思います | 5分 |

## 前回のアンケート
アンケートによると
> LT15人は詰め込み過ぎだったらしい

https://github.com/kizokukai/Kizokukai_LT/issues/33

**Comment by IkezoeMakoto** [comment]
fmfm

そう考えるとMAX10くらいっすかね～

LTって貴族会の中の人優先したり、もしくは外部の人優先したりってします？？

**Comment by Ushinji** [comment]
外部とか内部とかそういった優先付けは何もしていないですね。話したい人が話す感じですねー

**Comment by Ushinji** [comment]
自分もmax10人で良いと思います。

おそらく当日飛び込みLT時間を作ると思うので、10人で募集 -> 当日キャンセルで減る -> 飛び込みLTで帳尻合わせる。

かなっと。

**Comment by IkezoeMakoto** [comment]
じゃあ特に優劣なし10人で

発表時間の枠とかはどうします？前回は10分5分があったようですが

**Comment by Ushinji** [comment]
ぶっちゃけた話すると、5分枠、10分枠を作る目的ってはっきり議論された覚えがないのですよね。。。

とりあえず時系列は

- 第一回が10分枠だけ(理由は覚えてないです)
- 第二回が5分枠が追加された(議論されたかもしれませんが、覚えてないです)

ただ、一応自分の所感として、以下の通りかなと思っています。
- 5分枠は、もっと気軽にLTしてもらう枠
- 10分枠は、しっかりLTをしたい人向けの枠



で、以上を踏まえた個人的な意見としては、枠は２つあっても良いと思います。フランクに参加する人もいて良いと思うので。

ただ、人数は10分×5人、5分×5人というように固定したいです。理由は人数が流動出来だと事前にスケジュールが組むコストが高くなるからです(しかも当日に発表順番決めるとか。。。)

**Comment by IkezoeMakoto** [comment]
なるほど

それじゃ10分x5人, 5分x5人でいきますか

飛び入りは5分でいいですかね

**Comment by Ushinji** [comment]
飛び込みは5分で！良いと思います！

**Comment by IkezoeMakoto** [comment]
じゃあこれ反映僕やりますよ

**Comment by yumechi** [comment]
5分増やしたのは

* 登壇者増やす方針に移行したから
* 10分話すのってLTとしては長すぎでネタ持たなくない？5分なら軽いでしょ

くらいのノリだったよーな

**Comment by yumechi** [comment]
あと時間と人数はタイムスケジュールと密な関係にあるので、それを調整しつつですかね（タイムスケジュールのissueはどこでやってたのか記憶にない）
