### ISSUE TITLE
Conpass申し込み枠などの告知文以外の設定を残す方法

### ISSUE THREAD

**Issue by Ushinji** [teckup-tokyo/LT#50]
> 申し込み枠を
>
> 10分 5人
> 5分 5人
>
> にしてこの記載消すって方針はどうですかね？
>
> connpassの告知分からは消して、っていう話ですね。

意図伝わってるので大丈夫です！

その場合も、何かしらの形でレポジトリで残しておきたいですよね。。

どうするのが一番いいかな、、

_Originally posted by @IkezoeMakoto in https://github.com/kizokukai/Kizokukai_LT/pull/49_

**Comment by Ushinji** [comment]
以下の設定をどうやってリポジトリに残すかという話ですかね。

<img width="959" alt="2019-01-30 9 21 53" src="https://user-images.githubusercontent.com/24544727/51949912-f4e40780-2471-11e9-8de6-9abff41e589c.png">

**Comment by Ushinji** [comment]
思ったこととして、単純に `preparation.md` の Conpassページ公開に必要なことの欄に追記で良い気がする

**Comment by IkezoeMakoto** [comment]
> 思ったこととして、単純に `preparation.md` の Conpassページ公開に必要なことの欄に追記で良い気がする

個人的には `preparation.md` は準備するものリスト、のファイルで合って議論して決めたものを書くのは違うファイルにしたい気持ちだった

例えば `receptionist.md` とか

**Comment by Ushinji** [comment]
責務を分けるのは大事ですね。

自分は、`preparation.md` を見れば、LT会を進めていく上で必要なことがリスト化されており、そこの空欄を埋め、タスクを完了していけば、無事開催されるという目的と認識していた。

ただ、議論で決めた内容を記載するファイルで、目的を分けても良いですね。やってみますか。

今回は
- receptionist.md (参加者内訳)
- thema.md (テーマ決め)
- questionnaire.md (申し込み時のアンケート)

みたいなやつができていくイメージですかね。

**Comment by Ushinji** [comment]
テーマは、conpass.mdに記載するから要らないか。

**Comment by IkezoeMakoto** [comment]
そうっすね！入力欄が分かれてるものを別ファイルで管理するイメージ！

**Comment by IkezoeMakoto** [comment]
にへーしのこのコミットはどこに行ったんだろう？

**Comment by yutonihei** [comment]
なんかpushした時にブランチ名かなんかしらおかしくて消しちゃいましたの記憶があり...また会社PCからやってたので今そのブランチが手元にすらないので別途上げ直します...！

**Comment by IkezoeMakoto** [comment]
これやりますわー
