### ISSUE TITLE
告知するぞ

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#51]
connpassページ公開したら告知するぞ

**Comment by GOD-oda** [comment]
これ告知するならtwitterでもやりましょう！
文章を貰えれば流しますので！

**Comment by IkezoeMakoto** [comment]
告知―！！

> これ告知するならtwitterでもやりましょう！
> 文章を貰えれば流しますので！

あざますん

どの経路で告知流すかも決めておきたいっすね～

* twitter (貴族会、各人)
* facebook (貴族会、各人)


他なんかある？

**Comment by GOD-oda** [comment]
sns系だとだいたいその２つじゃないかなと思います
今はないけどinstagramとか？
あとはlinkedin？

**Comment by nmeguro** [comment]
Facebook、Twitter以外は、connpassのグループメールを定期的に飛ばすくらいかなあ

**Comment by yumechi** [comment]
流すのと担当者とフローまとめといたほうがいいんですかね？
こんな感じ？

* Facebook Group
    * connpass投稿した人
* Slack
    * connpass投稿した人（generalチャンネルへ）
* twitter
   * t.oda or m-hirao あたりで誰かがメンションくれれば（LTのチャンネルは流速が早いのでslackのgeneralのpostにスレッドでつけていただければ）

**Comment by IkezoeMakoto** [comment]
あー、そんな感じですかね〜！それで行きましょー

**Comment by IkezoeMakoto** [comment]
告知した
