### ISSUE TITLE
当日運営体制考える

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#52]
当日誰が何やるかを決める。

まずはどんな担当が必要かの洗い出しから

- [ ] 会場誘導(裏口なので)
- [ ] 司会
- [ ] 受付
- [ ] 会場準備
- [ ] タイムキーパー

**Comment by yutonihei** [comment]
役割分担的には司会、受付、会場準備くらいでしょうか。

**Comment by IkezoeMakoto** [comment]
会場準備はいつも3~4人くらいでやってるかな！

タイムキーパーとかはいらないかな？

**Comment by yutonihei** [comment]
タイムキーパー欲しいと思います！

**Comment by IkezoeMakoto** [comment]
社内でLT会やるときは

http://maruta.github.io/timekeeper/#t1=4:00&t2=05:00&t3=10:00&m=Click%20to%20edit%20this%20message

これを表示するPCを一台用意して前のほうの椅子に座ってる人に持たせてるだ

**Comment by yutonihei** [comment]
iPadにも似たようなアプリあったのでそれを使おうかなと思います。
ﾁｰﾝって鐘、ありますか？

**Comment by IkezoeMakoto** [comment]
鐘はないｗから↑のやつ使ってるｗ（音もなる

iPadでもできそう

**Comment by BBCapMegane** [comment]
そこは銅鑼じゃないいでしょうか(ぺちこんリスペクト)

**Comment by IkezoeMakoto** [comment]
>そこは銅鑼じゃないいでしょうか(ぺちこんリスペクト)

銅鑼鳴らしたい

**Comment by yutonihei** [comment]
https://www.amazon.co.jp/dp/B00RGE0NSM/ref=cm_sw_r_tw_dp_U_x_mzLuCbKBRG5
銅鑼

**Comment by BBCapMegane** [comment]
レンタル
https://www.pro-per.co.jp/category/2040631.html

**Comment by nmeguro** [comment]
司会は私でよければ今回もやらせて頂けますか……？

**Comment by IkezoeMakoto** [comment]
> 司会は私でよければ今回もやらせて頂けますか……？

やってもらえるの嬉しいんですが、できれば毎回少しずつ人変えていったほうが、ナレッジ分散できていいかなと思ってます。

**Comment by yutonihei** [comment]
是非お願いします！タイムキーパーやSli.do出せる画面あったら私それ担当しようかなーって気持ち

**Comment by nmeguro** [comment]
司会業はナレッジ分散難しいと思うんですよね。場数がものをいうアレだと思うので……。
あと個人的に、自社の勉強会の司会業もやらされがちなので力付けたいという思いもあり……。

**Comment by IkezoeMakoto** [comment]
> 司会業はナレッジ分散難しいと思うんですよね。場数がものをいうアレだと思うので……。
> あと個人的に、自社の勉強会の司会業もやらされがちなので力付けたいという思いもあり……。

なるほど！

そういう意図であれば、他に同じような人がいなければいいかなと思います～。

私は社内で十分機会あるのでいいですが、他の人がやりたいとかあれば譲ってあげたいなと思った程度なので！

**Comment by IkezoeMakoto** [comment]
https://github.com/kizokukai/Kizokukai_LT/issues/52#issue-404558587

更新

他ないっすかね。なければ担当を割り振っていきたい

**Comment by yumechi** [comment]
個人的には目黒さん以外も司会立ってもいいと思うし、前半後半で司会やりたい人がいればやればいいと思う（ちなみに実は結構司会はやりたい）

**Comment by IkezoeMakoto** [comment]
いいね！司会やりたい人がいるなら私はやったことないやりたい人を優先させたいと思ってます〜

次回以降もあるだろうしね！

**Comment by Ushinji** [comment]
えーと、当日のお仕事担当は以下の通りでしょうか？
自分はこれ以外に思いつかないのですが、なければ仕事の洗い出しはDONEで良いですか？

* [ ]  会場誘導(裏口なので)
* [ ]  司会
* [ ]  受付
* [ ]  会場準備
* [ ]  タイムキーパー

**Comment by Ushinji** [comment]
改めて、当日のお仕事担当は以下の通りでしょうか？

* [ ]   会場誘導(裏口なので)
* [ ]   司会
* [ ]   受付
* [ ]   会場準備
* [ ]   タイムキーパー

担当の洗い出しが完了したら、各担当に必要な人数を決めて、人選を進めたいでーす！！

**Comment by Ushinji** [comment]
各お仕事担当の人数ですが、以下は1人ずつで良いと思います

* 司会
* 受付
* タイムキーパー

で、以下のお仕事は何ぐらいいれば良いですかね？こちらは IkezoeMakoto さん、どうでしょうか？？

* 会場誘導(裏口なので)
* 会場準備

**Comment by IkezoeMakoto** [comment]
@Ushinji 

* 会場誘導(裏口なので) これも一人で大丈夫です～
* 会場準備 こちらは当日スタッフとして2~3人いてくれれば大丈夫かと思います～

**Comment by Ushinji** [comment]
あざっす。

当日の仕事分担を決めましょう！！！

* [x]   司会（1人） / nmeguroさん
* [ ]   受付（1人）
* [ ]   タイムキーパー（1人）

* [x]   会場準備（3人）/  運営の3人（Ushinji, IkezoeMakoto, nmeguro)
* [ ]   会場誘導（１人）/

現状こんな感じですかね。

あと仕事したいことあれば。

**Comment by BBCapMegane** [comment]
アキバです、
会場誘導やりますよー  
なんなら、会場準備も手伝います！

**Comment by Ushinji** [comment]
あっきーあざっす！会場誘導と、会場準備のお手伝いをお願いします！！！

あと、僕は受付やりますね。

現状で役割分担を更新をしました！

* [x]   司会（1人） / @nmeguro 
* [x]   受付（1人）/ @Ushinji 
* [ ]   タイムキーパー（1人）/ 

* [x]   会場準備（3人）/   @Ushinji  , @IkezoeMakoto , @nmeguro , @BBCapMegane 
* [x]   会場誘導（１人）/  @BBCapMegane

**Comment by IkezoeMakoto** [comment]
お、お、気づいたら役割大体埋まってる。

じゃあタイムキーパーやりますー

**Comment by IkezoeMakoto** [comment]
> アキバです、
> 会場誘導やりますよー
> なんなら、会場準備も手伝います！

あっきーありがと！！

**Comment by Ushinji** [comment]
あざっす!

これで、当日の役割分担はDONEですかね！次は、各仕事の内容を考えて、当日の動きを詰めていくことですね！

* [x]   司会（1人） / @nmeguro 
* [x]   受付（1人）/ @Ushinji 
* [x]   タイムキーパー（1人）/ @IkezoeMakoto 

* [x]   会場準備（3人）/   @Ushinji  , @IkezoeMakoto , @nmeguro , @BBCapMegane 
* [x]   会場誘導（１人）/  @BBCapMegane

**Comment by IkezoeMakoto** [comment]
当日の動きは別issueのほうがよさそう。

topic混ざるので、、

**Comment by Ushinji** [comment]
各お仕事の確認Issueをまとめる

- [ ] 司会 https://github.com/kizokukai/Kizokukai_LT/issues/73
- [x] タイムキーパー https://github.com/kizokukai/Kizokukai_LT/issues/74
- [x] 会場誘導 https://github.com/kizokukai/Kizokukai_LT/issues/75
- [ ] 会場準備
- [ ] 受付
