### ISSUE TITLE
終わった後の懇親会の準備

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#53]
懇親会は何貴族いくんですかね

**Comment by nmeguro** [comment]
ウィルゲートさんに一番近い貴族があればそこにしましょう。
毎回、connpassに設定できるアンケートで懇親会参加可否を聞いてるので、それをまとめて2週間～10日前に予約できればいいかなという感じです。

**Comment by IkezoeMakoto** [comment]
うち駅からやや歩くからあれだけど、たぶんいつもの渋谷西口店が一番近いはず

**Comment by nmeguro** [comment]
お店予約したっけ……？

**Comment by Ushinji** [comment]
まだ予約してないです！よ、予約をしないと。。。

場所は「渋谷西口店」ですかね。

**Comment by nmeguro** [comment]
一番近くが渋谷西口店しかないのでそこですかね！
予約お願いしますーーー

**Comment by Ushinji** [comment]
現状、懇親会参加者希望 + 運営で１８人です。

予約については、余裕持って20人で良いですかね？
減った場合は、改めて直前に連絡するようにする感じで。

予約する店は「鳥貴族　渋谷西口店」

時間はちょっと歩くので、１８：００〜（２h）で良いですかね？

**Comment by Ushinji** [comment]
予約完了したのでDONE

* 焼鳥屋　鳥貴族　渋谷西口店
* 18:00~20:00
* 20人
* 席のみ
