### ISSUE TITLE
LT会実施評価（アンケート）の準備

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#54]
アンケートちゃんと集めたくない？（集めたい

**Comment by nmeguro** [comment]
Googleフォームでやりましょう。あらかじめ用意しておいて当日にURL配布すれば良いかと。

**Comment by nmeguro** [comment]
内容考えないと。
- 全体満足度とコメント
- 発表者別満足度とコメント
- 今後やってほしいテーマとか
- その他

的な？

**Comment by IkezoeMakoto** [comment]
一旦上げる系

* 何経由で知ったか
* 次回も参加、登壇したいか
* 会場満足度
* 登壇者、参加者数は適切だったか
* 他に企画してほしいものとか
* 運営やってみたいかとか

**Comment by Ushinji** [comment]
参考までに、前回行なったアンケートです。
https://goo.gl/forms/LfwHHl3yHW6MdTtJ3

**Comment by nmeguro** [comment]
あっそうだ、前回やってたね！ 忘れていた。。。。
配布のタイミングがあんまりよくなかった記憶があるのでそこだけ徹底したいかも。
質問内容的にはどうかしら？

**Comment by yumechi** [comment]
（アンケート大事）

（あんまり急がなくてもいいトピックのように思えて、今がっつり決める必要もないなあと思ってます）

**Comment by IkezoeMakoto** [comment]
これもそろそろ準備しないと、、
