### ISSUE TITLE
実施後振り返り

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#55]
とったアンケートと準備～当日の実施状況を振り返り次回につなげる

**Comment by IkezoeMakoto** [comment]
あらかじめ、集まって振り返りする予定立てておきたいですね。

**Comment by IkezoeMakoto** [comment]
予定調整しておきたい気持ちですが、皆さんどうです？

**Comment by nmeguro** [comment]
あっ振り返りしたいです！
毎回KPT挙げてはいるものの、直接会話することがない、というのもあり（少なくとも私は）忘れがちなので……

**Comment by IkezoeMakoto** [comment]
https://chouseisan.com/s?h=879008e82c514af999fb1e9041704c62

**Comment by IkezoeMakoto** [comment]
3/4でいきましょう！！

**Comment by IkezoeMakoto** [comment]
日程決まったのでクローズ

各自予定空けておいてください～

**Comment by IkezoeMakoto** [comment]
あ、すみません。

3/4予定入ってしまっていた、、、

3/6でお願いします！
