### ISSUE TITLE
レポジトリ名が冗長

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#56]
kizokukai/LT

でいい気がしている

何ならディレクトリも

`LT_{開催番号}/` じゃなくて `{開催番号}/` でいいと思う

**Comment by Ushinji** [comment]
`{開催番号}/ ` はマジックナンバーで、なんの数字か分からない気が。。という気持ちもあります。

ただ、ブランチ名は`kizokukai/LT`は賛成ですね。

**Comment by IkezoeMakoto** [comment]
完了
