### ISSUE TITLE
[第3回] 当日スケジュールについて考える

### ISSUE THREAD

**Issue by Ushinji** [teckup-tokyo/LT#57]
## 議題
当日のスケジュールについて議論し、決定する

## 現在の決定事項
* LT登壇者
  * 10分枠：5人
  * 5分枠：5人
* あととびこみLTとか

## 補足資料

* 前回のスケジュール

| スケジュール             | 開始  | 終了  |
| ---------------- | ----- | ----- |
| 受付開始         | 13:00 | 13:30 |
| LTの説明・アイスブレイク  | 13:30 | 13:45 |
| 発表①            | 13:45 | 14:20 |
| 歓談・休憩①       | 14:20 | 14:40 |
| 発表②            | 14:40 | 15:15 |
| 歓談・休憩②       | 15:15 | 15:35 |
| 発表③            | 15:35 | 16:05 |
| 歓談・休憩③       | 16:05 | 16:25 |
| 飛び込みLT・宣伝タイム | 16:25 | 17:00 |
| 締め・撤収         | 17:00 | 17:30 |

**Comment by Ushinji** [comment]
一旦、今回のスケジュールのたたきを作った。

一回の発表時間を減らし、回数を増やした。

| スケジュール             | 開始  | 終了  |時間 |
| ---------------- | ----- | ----- |----- |
| 受付開始  | 13:00 | 13:30 |30min |
| LTの説明・アイスブレイク  | 13:30 | 13:40 |15min |
| 発表①（5分×2、10分×1） | 13:45 | 14:05 |20min |
| 歓談・休憩①       | 14:05 | 14:25 |20min |
| 発表②（5分×1、10分×2）  | 14:25 | 14:50 |25min |
| 歓談・休憩②       | 14:50 | 15:15 |25min |
| 発表③ （5分×1、10分×1）| 15:15 | 15:30 |15min |
| 歓談・休憩③| 15:30 | 15:50 |20min |
| 発表④ （5分×1、10分×1）| 15:50 | 16:05 |15min |
| 歓談・休憩④| 16:05 | 16:25 |20min |
| 飛び込みLT | 16:25 | 16:45 |20min |
| 会場提供社様 LT | 16:45 | 16:50 |5min |
| 締め| 16:50 | 17:00 |10min |

**Comment by yutonihei** [comment]
良いかと思いますー！

**Comment by IkezoeMakoto** [comment]
最初の説明のとこで会場説明とかしておかなくていいすかね？

**Comment by yumechi** [comment]
主観だけど休憩が多すぎかも。

30〜40分はLT聞けるからLT、休憩交流タイムのブロック数の調整したほうが良さげ。

**Comment by yutonihei** [comment]
例えばの案をだしていただけると嬉しいのですが、yumechiさんの修正案の自己解釈はこうです。

| スケジュール             | 開始  | 終了  |時間 |
| ---------------- | ----- | ----- |----- |
| 受付開始  | 13:00 | 13:30 |30min |
| LTの説明・アイスブレイク  | 13:30 | 13:45 |15min |
| 発表①（5分×2、10分×3） | 13:45 | 14:30 |45min |
| 歓談・休憩①                       | 14:30 | 14:50 |20min |
| 発表②（5分×3、10分×2） | 14:50 | 15:25 |35min |
| 歓談・休憩②                       | 15:25 | 15:45 |20min |
| 飛び込みLT                           | 15:45 | 16:05 |20min |
| 会場提供社様 LT                  | 16:05 | 16:10 |5min |
| 歓談                                     | 16:10 | 16:50 |40min |
| 締め                                     | 16:50 | 17:00 |10min |

って感じですか？
この調整をしたところで最後の歓談の時間が気持ち長いような気もする。開始を30分押してもいいのかもしれない・・・？

**Comment by Ushinji** [comment]
> 最初の説明のとこで会場説明とかしておかなくていいすかね？

IkezoeMakoto さんのコメントについては、必要ですね。ありがとうございます！ 初めの`LTの説明・アイスブレイク`の時間に忘れずやりましょう！

で、初めの時間と、締めの時間の内容は、別途詳しく議論しましょう！

**Comment by Ushinji** [comment]
yumechi さん、 歓談/休憩タイムの数を減らすと、１回の休憩時間を増える感じになりますね。

また、yutoniheiさんのコメントにあるように、休憩時間を長く感じるのであればスケジュールを減らすという選択肢もありますね。

で、僕の最初に提案したスケジュールについて説明すると、特徴は「発表と休憩時間の回数が多い」です。この特徴の何が良いかというと、休憩時間が来るたびに会話する人/グループが変わると思うので、より多くの人と会話するきっかけを提供できると期待しています(当然、司会がうまくハンドリングする必要はあるかもですね)

スケジュールについて正解/不正解はないので、ここまで来ると議論の主題は「貴族LT会で参加者に何を提供したいかという話」かなと感じました。

**Comment by IkezoeMakoto** [comment]
例えば質問タイムをとるとかしてもいいかもしれないですね

発表5分 質問(入れ替え時間)2分

発表10分 質問(入れ替え時間)3分

とか

>「貴族LT会で参加者に何を提供したいかという話」
これはたぶんもちろん大事ですね。

交流？発表機会？技術情報？

何を一番にするかは議論しておいたほうがいいですね。何かを決めるときの指標になると思うので

**Comment by nmeguro** [comment]
>貴族LT会で参加者に何を提供したいかという話

はテーマに直結している気がするので、テーマ決める中で考えると良いかも？

**Comment by IkezoeMakoto** [comment]
懇親会の時間も任意ってのがわかる状態にして入れておいた方がいいかなと思った。

イメージ

| スケジュール             | 開始  | 終了  |時間 |
| ---------------- | ----- | ----- |----- |
| 受付開始  | 13:00 | 13:30 |30min |
| LTの説明・アイスブレイク  | 13:30 | 13:40 |15min |
| 発表①（5分×2、10分×1） | 13:45 | 14:05 |20min |
| 歓談・休憩①       | 14:05 | 14:25 |20min |
| 発表②（5分×1、10分×2）  | 14:25 | 14:50 |25min |
| 歓談・休憩②       | 14:50 | 15:15 |25min |
| 発表③ （5分×1、10分×1）| 15:15 | 15:30 |15min |
| 歓談・休憩③| 15:30 | 15:50 |20min |
| 発表④ （5分×1、10分×1）| 15:50 | 16:05 |15min |
| 歓談・休憩④| 16:05 | 16:25 |20min |
| 飛び込みLT | 16:25 | 16:45 |20min |
| 会場提供社様 LT | 16:45 | 16:50 |5min |
| 締め| 16:50 | 17:00 |10min |
| 懇親会（アンケート参加回答者）| 18:00 | 21:00 | 3h |

**Comment by IkezoeMakoto** [comment]
サポー〇ーズみたいに冒頭に自己紹介とかいらないかな？

**Comment by nmeguro** [comment]
前回はアイスブレイクで適当に4人一組とか作って5分くらいで自己紹介しあう時間設けました

**Comment by Ushinji** [comment]
あと、スケジュールに関して考える必要がある点はありますか？
これまでの議論を踏まえると、

* 各発表のあと `質問+入れ替え時間を設定する` 
  * 加えて、質問拾う方法
    * `sli.do` 、`スプレッドシート`、`twitterハッシュタグ`

ぐらいですか。

アイスブレイクの時間に、自己紹介タイムを設定する方向で良いかと！！

**Comment by nmeguro** [comment]
では開始のアイスブレイクで自己紹介タイム設けますね。
前回同様、その場で適当に組を作ってもらい、5分程度で。

質問の拾い方は、sil.do カッコイイなと思うものの少しハードル高い気がしているので、スプシで良いかな？と個人的には思ってます。Twitterはアカウント持っていないといけないし。

**Comment by Ushinji** [comment]
質問の拾い方について、

> スプシで良いかな？と個人的には思ってます。

スプレッドシートなのですが、どうやって集計するのか自分が把握できていないので、具体的な方法を教えて頂いてもいいですか？

スプレッドシートのURLを配布して、そこに質問を書いてもらうという形式でしょうか？？

**Comment by nmeguro** [comment]
>スプレッドシートのURLを配布して、そこに質問を書いてもらうという形式

それ！
リアルタイムでセルに誰かのカーソルが当たっているのが分かるので、記載中に上書きしちゃった、というのは起こりにくいはず。
[https://docs.google.com/spreadsheets/d/1qMtZ8T02C6QGYbeJyu3_NWkqB6sZbMbvXjaxFnYFmZA/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1qMtZ8T02C6QGYbeJyu3_NWkqB6sZbMbvXjaxFnYFmZA/edit?usp=sharing)
こんな感じのスプシ用意すればいいかなと。使用方法は当日の最初にお伝えする感じで。

**Comment by IkezoeMakoto** [comment]
質問用のアンケートフォーム作ればよさそうかな～と思ってた。

スプシはリード権限で共有すれば見て回答もできるし

**Comment by Ushinji** [comment]
なるほど！しかも、スプシの見本も作ってもらい、わかりやすいです！あざっす！
また、アンケートフォームもありですね！

もう一つ質問ですが、こちらについては全体で共通ですか？それとも発表ごとに別シートを用意する感じでしょうか？

**Comment by nmeguro** [comment]
アンケフォームいいっすねぇ、悩む。
スプシはライブ感出るところだけど、誰かが書き始めないと誰も書かない可能性があるところでちょっとネックかも。
フォームは集計楽だけど、ライブ感が薄いなあとか思いました。
一長一短。

スプシにするなら1シートで管理かなと思ってます。
登壇者10人いるから10シートになるとちょっと見えにくいし、1人にたいして何十個も質問が出てくることは無いかなと想定しているので。

**Comment by Ushinji** [comment]
なるほど。確かに複数シートになると分かりづらいというのは同意ですねー

個人的な意見として、 入力の操作性についてアンケートフォームの方が楽だと思うので、入力フォーム推しです(スプレッドシートは改行はcrtl+enterですし。。。)

ライブ感については、集計後のスプレッドシートでもリアルタイム更新されれば、多少は感じられるのではないかな？？試してみないとわからないですが(笑)

<br>

あと、加えてスプレッドシートやアンケートフォームのURLをどうやって配布するかについても考えないとですね。QRコードはスマホ限定ですし。。。個人的に、PCフレンドリーな方法が嬉しいです。

**Comment by IkezoeMakoto** [comment]
>あと、加えてスプレッドシートやアンケートフォームのURLをどうやって配布するかについても考えないとですね。QRコードはスマホ限定ですし。。。個人的に、PCフレンドリーな方法が嬉しいです。

ハッシュタグに乗せてツイッターでどうでしょうかね？

**Comment by Ushinji** [comment]
twitterで流すなら別に良いですかね。アカウントがなくてもツイートは確認できますし。
あと、不特定多数に公開しますが、まあ見る人限られているし問題ないか。。。。。


そこらへんsli.doの方が、やり易いですね。sli.doをgoogle検索からアクセスして、4桁のコードを入れるだけでアクセスできますので。

**Comment by nmeguro** [comment]
じゃあ今回はGoogleフォーム用意しましょう！ 後日作ります。

URL配布はbit.lyで短くて可読性のあるURLを生成して当日ホワイトボードに書いておくで良いかなと思ってました。

**Comment by Ushinji** [comment]
短縮URLなら、入力してもらうの楽ですね！確かに！
その方向性で行きましょう！

> じゃあ今回はGoogleフォーム用意しましょう！ 後日作ります。

こちら、作成をまかせちゃってもよろしいですかね？お願いします！

**Comment by Ushinji** [comment]
では、質問を収集する方法が決まったので、質問タイム+次発表者の準備の時間を考えますか？

発表者1人に対して、3分ぐらいですかね？
質問が出るか不透明なので、5分は多いような気がする。。。。。

**Comment by Ushinji** [comment]
暫定で質問時間を3分として、変更を反映したスケジュールを作りました。

単純に3分足すと14:16とかキリが悪くなるんで以下のように概算しています

* 発表者3人(発表①、発表②)は10分追加(3min×3人≒10min)
* 発表者2人(発表③、発表④)は5分追加(3min×2人≒5min)

質問時間を追加した分は、休憩時間が減らしました。どうでしょうか？？？

| スケジュール             | 開始  | 終了  |時間 |
| ---------------- | ----- | ----- |----- |
| 受付開始  |13:00|13:30|30min|
| LTの説明・アイスブレイク  |13:30|13:45|15min|
| 発表①（5分×2、10分×1）|13:45|14:15|30min|
| 歓談・休憩①       |14:15|14:25|10min|
| 発表②（5分×1、10分×2）  |14:25|15:00|35min|
| 歓談・休憩②       |15:00|15:15|15min|
| 発表③ （5分×1、10分×1）|15:15|15:35|20min|
| 歓談・休憩③|15:35|15:50|15min|
| 発表④ （5分×1、10分×1）|15:50|16:10|20min|
| 歓談・休憩④|16:10|16:25|15min|
| 飛び込みLT |16:25|16:45|20min|
| 会場提供社様 LT |16:45|16:50|05min|
| 締め|16:50|17:00|10min|
| 懇親会（アンケート参加回答者）| 18:00 | 21:00 | 3h |

**Comment by IkezoeMakoto** [comment]
良いと思います～。ありがとうございます！

あ、アンケートの回答時間だけ最後に入れたほうがいいかも

たぶん締め10分もいらないので締めの前に回答時間5分作ればいいかな

**Comment by Ushinji** [comment]
> アンケートの回答時間だけ最後に入れたほうがいいかも


うっす。明記しときますか。
↓

| スケジュール             | 開始  | 終了  |時間 |
| ---------------- | ----- | ----- |----- |
| 受付開始  |13:00|13:30|30min|
| LTの説明・アイスブレイク |13:30|13:45|15min|
| 発表①（5分×2、10分×1）|13:45|14:15|30min|
| 歓談・休憩①       |14:15|14:25|10min|
| 発表②（5分×1、10分×2）  |14:25|15:00|35min|
| 歓談・休憩②       |15:00|15:15|15min|
| 発表③ （5分×1、10分×1）|15:15|15:35|20min|
| 歓談・休憩③|15:35|15:50|15min|
| 発表④ （5分×1、10分×1）|15:50|16:10|20min|
| 歓談・休憩④|16:10|16:25|15min|
| 飛び込みLT |16:25|16:45|20min|
| 会場提供社様 LT |16:45|16:50|5min|
| アンケート回答|16:50|16:55|5min|
| 締め|16:55|17:00|5min|
| 懇親会（アンケート参加回答者）| 18:00 | 21:00 | 3h |
