### ISSUE TITLE
[第３回] Conpassページから参加申し込みする際のアンケート

### ISSUE THREAD

**Issue by Ushinji** [teckup-tokyo/LT#58]
## 目的
Conpassページから参加申し込みする際のアンケートの項目を決める。
以下スクリーンショットのあれです。

<img width="681" alt="2019-02-01 9 17 15" src="https://user-images.githubusercontent.com/24544727/52094412-69e64700-2602-11e9-82c1-b8daae804507.png">

## 提案

前回から必要な項目だけ抜粋しました。

```
1. 【LTするひと】イベントページ掲載用のタイトル（大まかな発表内容でも可）をご記入ください。
  -  回答タイプ：フリーテキスト

2. 【LTするひと】イベントページ掲載用の「発表者名」をご記入ください。
  -  回答タイプ：フリーテキスト

3. 【LTするひと】Twitterやブログ等をお持ちで「イベントページに掲載しても大丈夫！」という方は、URLをご記入ください。
  -  回答タイプ：フリーテキスト

4.  【全員】懇親会に参加しますか？！ ※会場周辺 ※自費
  -  回答タイプ：ラジオボタン(もち参加！ or ちょっと遠慮しときます)

5. 【全員】(任意)あなたが開催されたら参加したいイベントがあれば、お願いします！
  -  回答タイプ：フリーテキスト
```

**Comment by IkezoeMakoto** [comment]
こちらまとめありがとうございます！！

概ねそのままでいいかなと思いましたが、一点だけ！

>5. 【全員】(任意)あなたが開催されたら参加したいイベントがあれば、お願いします！

に関しては開催後のアンケートでいいような気がした。

**Comment by Ushinji** [comment]
> 【全員】(任意)あなたが開催されたら参加したいイベントがあれば、お願いします！
> に関しては開催後のアンケートでいいような気がした。

確かに！いいと思います！

**Comment by Ushinji** [comment]
くぅ～疲れましたw これにて完結です！ https://github.com/kizokukai/Kizokukai_LT/pull/60
