### ISSUE TITLE
名札欲しい

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#63]
名札欲しい

確かに。
名前以外に、ペンの色とかで、登壇者かどうか、何系エンジニアか、が分かるような仕組みで。

_Originally posted by @IkezoeMakoto in https://github.com/kizokukai/Kizokukai_LT/issues/33#issuecomment-460283591_

**Comment by Ushinji** [comment]
自分も欲しいと思っています！

で、これの実現方法ですが **名札ケース** を準備がありますが、どうやるのが良いするかですね。
100均で売ってるから、人数分(40人？）用意しますか？ 4000円。

紙とペンは。。。会場様。。。どうか、ご用意を。。。。

**Comment by IkezoeMakoto** [comment]
紙とペンは全然いいですが、いつもだと、名刺を入れてもらったりしてますね。

書いてもらうのも面倒なので

**Comment by Ushinji** [comment]
名刺よりも、自分で書いてもらった方が良い気がしてます！
ワンチャンtwitter名とか書いたりでもいいと思いますしー

あと、純粋に色々自分で書いた方が楽しそう！そして、だいたい名刺は忘れるんすよねw

**Comment by IkezoeMakoto** [comment]
なるほど、意外とみんな書きたいんですかね、、

まぁ紙とペンくらいは用意できると思うので、問題はないです

**Comment by IkezoeMakoto** [comment]
これケースどうします？どこから費用出します？？

**Comment by Ushinji** [comment]
アスクルさんにて、イベント用名札ケースについて調べた。

* 50個
* ￥1,522（税込）

https://www.askul.co.jp/p/662150/?sc_e=cp_p_as_go_pl_c&utm_source=go&utm_medium=PLA&utm_campaign=PLA_All&gclid=EAIaIQobChMItp_l9dDQ4AIVwrWWCh1HPggBEAQYASABEgIxPvD_BwE

安くない？ポケットマネーで買っても良いレベル。

**Comment by Ushinji** [comment]
こちらのシール形式の名札を購入する方針でいきたいと思いますが、よろしいでしょうか？

https://www.askul.co.jp/p/9371055/?sc_e=cp_p_as_go_pl_c&utm_source=go&utm_medium=PLA&utm_campaign=PLA_All&gclid=EAIaIQobChMIk4O119rV4AIViraWCh2pzwNZEAQYASABEgIp2PD_BwE

**Comment by IkezoeMakoto** [comment]
買いましょう！

**Comment by Ushinji** [comment]
じゃ、自分が買っておきますね！
