### ISSUE TITLE
タイムスケジュールの見直し

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#64]
交流時間も足りなかったらしい

といいつつ20分×3回だったし決して少なかった訳ではない。
発表者が多いから質問も沢山あって足りないとか？
あるいは参加者が他者交流大好きマンの集まりだった可能性。意識高くて良い。

_Originally posted by @IkezoeMakoto in https://github.com/kizokukai/Kizokukai_LT/issues/33#issuecomment-460283725_

**Comment by Ushinji** [comment]
こちらについては、前回よりも発表者数も減ったことで、交流時間は増えているので、問題ないと感じますが。。。

これは、1回あたりの交流時間を増やした方が良いという意見でしょうかね？うーむわからん。

ただ、判断のしようがないので、今回の発表者数を減らした施策をやってみて、再度参加者アンケートの結果をみて判断で良いのではないでしょうか？

**Comment by IkezoeMakoto** [comment]
前回を知らないので、あれですが、交流好きマンは懇親会で勝手に交流してくれ、でもいいかと

**Comment by IkezoeMakoto** [comment]
>今回の発表者数を減らした施策をやってみて、再度参加者アンケートの結果をみて判断で良いのではないでしょうか？

これで！
