### ISSUE TITLE
実施後アンケートをもっと集めたい

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#65]
回答数が思ったより少ない

これは配布タイミングが後日になってしまったのが要因か。
設問自体は適切だったと思う。
ので次回はちゃんとイベントの最後でお知らせする。

_Originally posted by @IkezoeMakoto in https://github.com/kizokukai/Kizokukai_LT/issues/33#issuecomment-460283839_

**Comment by Ushinji** [comment]
> これは配布タイミングが後日になってしまったのが要因

ですです。

そして、その原因は最後のクロージングの準備をしていなかったこと。
最後、ここでアンケートをお願いする予定だったけど、すっかり忘れていた。

なので、対策の提案は以下の２つです。
- そもそも最後のクロージングの内容を司会に丸投げせず、みんなで決める
- 飛び込みLTなどで時間が押しても、必ず決まった時間に最後のクロージングを始める

**Comment by IkezoeMakoto** [comment]
クロージングのスライド作るのであれば、そこにQRコード乗せておけば、忘れないかと。

あと、時間が心配であればタイムスケジュールにクロージングの時間も入れておけばOK

**Comment by nmeguro** [comment]
クロージングのスライドは簡単に作る予定です！
（今後もイベントやっていきますよ、と、懇親会のお店のお知らせ）
その中にアンケートの短縮URLとQRコード載せたいです。

ちなみにアンケートの内容って前回と同様でいいです？？
前回のアンケって誰作ったんでしたっけ？ 宇山くん？

**Comment by Ushinji** [comment]
事後アンケートの素案作りましたー
ただ、前回LT時の内容と同じですがw

一旦、 @nmeguro さんと、 @IkezoeMakoto さんに閲覧、編集権限与えてますー

https://docs.google.com/forms/d/1WqNAJwW6iOjsuif5I157t5--jBcEx-xlNvgZUXP6-qY/edit

**Comment by IkezoeMakoto** [comment]
運営に参加してみたいかどうかとか、ヒアリング項目あってもいいかなと思った。

あ、でも連絡先も一緒に聞かないといけないな

**Comment by nmeguro** [comment]
>運営に参加してみたいかどうかとか、ヒアリング項目あってもいいかなと思った。


たしかにちょっと欲しいかも。

**Comment by Ushinji** [comment]
> 運営に参加してみたいかどうかとか、ヒアリング項目あってもいいかなと思った。

こちら追記しました。具体的に以下の２つの質問を追加しました

- LT会の運営に興味はありますか？ （はい/いいえ）
- 【「LT会の運営に興味はありますか？」で「はい」と答えた方のみ】 連絡先(メールアドレスやtwitterアカウントなど)を記入してください（記述式）

**Comment by IkezoeMakoto** [comment]
ありがとうございます！いいと思います！！
