### ISSUE TITLE
質問を拾う方法を考える

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#66]
- 質問を拾う方法を考える
  - sil.doだと格好良いけど、実はスプシで良いのでは。
  - スプシなら質問履歴も残るし。

_Originally posted by @nmeguro in https://github.com/kizokukai/Kizokukai_LT/issues/32#issuecomment-443992336_

**Comment by IkezoeMakoto** [comment]
これはにへーさんとこないだ話したけど、プロジェクタしかないので、二台使ってできそうならsli.doで
無理そうならスプシかなぁ

**Comment by IkezoeMakoto** [comment]
https://github.com/kizokukai/Kizokukai_LT/issues/57#issuecomment-464620595

きっと @nmeguro さんがやってくれる

**Comment by nmeguro** [comment]
http://bit.ly/kizokult3qa
こんなフォームで大丈夫です？？
ヘッダ画像が欲しいところ（800x200以上のサイズじゃないといけないので、ロゴだと小さくて入れられない。。）

**Comment by Ushinji** [comment]
ファーム作成あざっす！
良いんじゃないですか！！

ヘッダーは必ずしも無くてもよいのですが、なんか作りますか。自分が時間を見つけて作っときます！

**Comment by Ushinji** [comment]
いい感じのフォームを作ってくれたのでクローズ。
あとは振り返りで
