### ISSUE TITLE
運営メンバーの追加

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#67]
* 運営メンバーの追加
  * 正直3人は厳しい
  * 当日作業メンバーを募集しておくべき（今回で言えば2〜3名）

_Originally posted by @yumechi in https://github.com/kizokukai/Kizokukai_LT/issues/32#issuecomment-445509782_

**Comment by IkezoeMakoto** [comment]
これなー、場合によっては当日スタッフ枠を作ってもいいが、、、まだはやいという気持ち

他何あるかなーrandomとかで公募したら手伝ってくれるかな？

**Comment by Ushinji** [comment]
これについては、以下の当日運営体制で必要な仕事がFixしてから、必要な人員まで何人協力が必要なのか決めれば良いと思います。
https://github.com/kizokukai/Kizokukai_LT/issues/52

**Comment by yumechi** [comment]
https://github.com/kizokukai/Kizokukai_LT/issues/16

これベースに考えれば推測はつけやすいと思う（役割は適宜見直してください）

**Comment by IkezoeMakoto** [comment]
アンケートに含めたのでいったんクローズ
