### ISSUE TITLE
運営の当日スケジュールについて決める

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#72]
運営側の当日のスケジュールについて決める

_Originally posted by @IkezoeMakoto in https://github.com/kizokukai/Kizokukai_LT/issues/52#issuecomment-466282758_

**Comment by IkezoeMakoto** [comment]
とりあえずこんな感じ？

| 時間        | 内容                 | 役割(人)                              |
|-------------|----------------------|---------------------------------------|
| 11:30~12:00 | 前入り               | みんな                                |
| 12:00~13:00 | (ごはんでも食べながら)打ち合わせ、会場準備 | みんな                                |
| 13:00~13:30 | 受付                 | 会場誘導(あっきー), 受付(うやまさん)  |
| 13:30~13:45 | 導入                 | 司会(めぐろさん), タイムキーパー(zoe) |
| 13:45~17:00 | LT                   | 司会(めぐろさん), タイムキーパー(zoe) |
| 17:00~17:30 | 片付け               | みんな                                |
| 18:00~20:00 | 懇親会               | みんな                                |
|             |                      |                                       |

**Comment by Ushinji** [comment]
了解です！ 良いと思います！
12:00までに会場着すれば良いですね！

**Comment by Ushinji** [comment]
無事終了したのでクローズ。あとは振り返りで。
