### ISSUE TITLE
[第3回] タイムキーパーのお仕事を確認する

### ISSUE THREAD

**Issue by Ushinji** [teckup-tokyo/LT#74]
タイムキーパーのお仕事を確認！！！

お仕事は以下の通りかと
- 各LTにて時間を計測

で、確認事項として、

- リアルタイムで時間を表示する画面を用意する？
- 1分前になったら何かする？(音鳴らすとか、身振り手振りで動作をするとか)

どうでしょうか？

**Comment by IkezoeMakoto** [comment]
>リアルタイムで時間を表示する画面を用意する？

これの想定でした。

一つ問題があって、私がタイムキーパーなんですが、私も登壇するのでその際、誰かにお願いしないといけないという、のを失念していました。

**Comment by Ushinji** [comment]
まずゾエさんのLT時はタイムキーパーは誰かに変わってもらうことを、事前に把握しておけば大丈夫かと！

そして、「リアルタイムで時間を表示する画面を用意」で行きましょう！画面は誰かのPCか、タブレットを使って表示ですかね。

また、良い感じに時間を表示してくれるWebサービスorアプリがあれば嬉しいですね。誰か知っていますか？？

**Comment by IkezoeMakoto** [comment]
いつもこれ使ってます！

http://maruta.github.io/timekeeper/#t1=4:00&t2=05:00&t3=10:00&m=Click%20to%20edit%20this%20message

**Comment by Ushinji** [comment]
お！TimeKeeperいいっすね！問題なさそう！

それじゃ、タイムキーパーのお仕事確認は以上でよろしいでしょうか？

**Comment by IkezoeMakoto** [comment]
OKでっす！

**Comment by Ushinji** [comment]
うっす！では、タイムキーパーの話はDONEで！
