### ISSUE TITLE
振り返り

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#77]

**Comment by nmeguro** [comment]
一応貼っておきますが、質問フォームからの質問はこれで、
[https://docs.google.com/spreadsheets/d/1DJokIcGmpFp8iMtxrZQLGkAFXJQchZoOW7PL83m2dxI/edit#gid=1758967072](https://docs.google.com/spreadsheets/d/1DJokIcGmpFp8iMtxrZQLGkAFXJQchZoOW7PL83m2dxI/edit#gid=1758967072)

アンケ結果はこれです～。
[https://docs.google.com/spreadsheets/d/1vNi6lUCgjo_TgQV6OkSAes1vQgi1YV_Ehs6fQOIomaE/edit#gid=1509158820](https://docs.google.com/spreadsheets/d/1vNi6lUCgjo_TgQV6OkSAes1vQgi1YV_Ehs6fQOIomaE/edit#gid=1509158820)

**Comment by IkezoeMakoto** [comment]
念のため 日程は 3/6

**Comment by IkezoeMakoto** [comment]
振り返った
