### ISSUE TITLE
7月開催LTについて決める

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#80]
ref: #78 
```
次回LT会開催について
時期: 7月初旬
場所: opt(仮)
```
を進めていきましょう

_Originally posted by @IkezoeMakoto in https://github.com/techup-tokyo/LT/issues/79#issuecomment-478973667_

**Comment by IkezoeMakoto** [comment]
テーマ決める

**Comment by IkezoeMakoto** [comment]
会場確定させる

確定したらしい

```
まこにゃん [9:15 PM]
@n.meguro 会場の貸し出し可能かどうか、確認って出来ました～？


n.meguro [9:15 PM]
いけそうです！
```

**Comment by IkezoeMakoto** [comment]
日程確定させる

**Comment by IkezoeMakoto** [comment]
コンパスページ作成

**Comment by IkezoeMakoto** [comment]
タイムスケジュール作る

**Comment by IkezoeMakoto** [comment]
役割分担決める

**Comment by IkezoeMakoto** [comment]
7月初旬開催予定なので、6月初旬にはイベントページを公開しておきたいです。と、考えると5月中に諸々内容を詰めたいと思うのでご協力お願いします〜

**Comment by IkezoeMakoto** [comment]
https://chouseisan.com/s?h=d76b0a17a94f481182d55baaa2edfebf

**Comment by yumechi** [comment]
回答してみた

**Comment by IkezoeMakoto** [comment]
7/13っぽい

**Comment by IkezoeMakoto** [comment]
日程決まったので進めていきますよ〜

**Comment by IkezoeMakoto** [comment]
当日までにやること

- 当日役割分担決め(司会、タイムキーパー、会場案内、受付、会場準備)
    - (運営メンバーの)当日の詳細なタイムスケジュール確定
- 事前告知メッセージ作成と送信
- LT会実施アンケート作成
- オープニングスライド、クロージングスライド作成(おそらく司会担当)
- 名札準備？(前回の余りがあればそれでも)
- 懇親会準備？(事前予約など)

**Comment by IkezoeMakoto** [comment]
チケット切って行く気持ちだけ高めている（週明けくらいにばりばりやる）

**Comment by IkezoeMakoto** [comment]
思ってたより集客できてないので、終了時間が早まりそう。

**Comment by IkezoeMakoto** [comment]
振り返りする

**Comment by IkezoeMakoto** [comment]
終わった
