### ISSUE TITLE
役割決め

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#83]
* 司会1人（オープニング、クロージングも）
* タイムキーパー1人（LTのタイムキーパー兼会全体のタイムキーパーも）
* 会場案内1人（入館等あれば）
* 受付2人（会の参加登録している人か確認、名札配ったり）
* 会場準備（当日運営全員で）

_Originally posted by @IkezoeMakoto in https://github.com/teckup-tokyo/LT/issues/80#issuecomment-499420095_

**Comment by IkezoeMakoto** [comment]
今週中くらいまでに各自やりたいところあれば立候補してください。なければ私が独断と偏見で割り振りマス。

**Comment by BBCapMegane** [comment]
受付やります！

**Comment by IkezoeMakoto** [comment]
こんなかんじで割り振りたいんですが、皆さんどうですかねー？

* 司会1人（オープニング、クロージングも） @nmeguro 
* タイムキーパー1人（LTのタイムキーパー兼会全体のタイムキーパーも） @RyoheiKunimi 
* 会場案内1人（入館等あれば） @yutonihei 
* 受付2人（会の参加登録している人か確認、名札配ったり） @BBCapMegane @DAdDY0055

**Comment by yumechi** [comment]
よしなにサポート回ります

**Comment by DAdDY0055** [comment]
すいません、今見ました。
受付OKです！！

**Comment by BBCapMegane** [comment]
https://github.com/teckup-tokyo/LT/issues/87
↑で出たのですが、自分受付兼、会場案内します。

入り口で案内スタッフが誰もないいという状況を防ぐためです。
イメージ的には、来場されたら @BBCapMegane がLT会場まで案内、受付
@yutonihei  さんは入り口にいてもらうみたいなイメージです
(まぁ交代交代でもいいかも)

**Comment by IkezoeMakoto** [comment]
https://github.com/teckup-tokyo/LT/issues/83#issuecomment-504663639

これで行く
