### ISSUE TITLE
LT会実施アンケート作成

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#85]
- LT会実施アンケート作成

会の内容のFBなどヒアリングしたいことをまとめておいてアンケートを作る
短縮URLを発行してQRコードを発行してクロージングLTに入れる

_Originally posted by @IkezoeMakoto in https://github.com/teckup-tokyo/LT/issues/80#issuecomment-499420095_

**Comment by IkezoeMakoto** [comment]
こちらも同様に一旦私タスクにしてます。やりたい人いたらコメントください

**Comment by nmeguro** [comment]
Slackにも共有したのですが、司会用スライドにQRコード載せたりする兼ね合いもあるので、私の方で一旦作成しますね。

**Comment by nmeguro** [comment]
フォームとりあえず作りました。
[https://forms.gle/pkB64LLWpt2U5oQp9](https://forms.gle/pkB64LLWpt2U5oQp9)

質問内容こんな感じです。過不足あればお願いします。
ちなみに「名前」「職種」は、どういう人がどういう内容に興味を持ってくれたか知りたいなと思ったので設けてみました。不要なら消します。

```
- お名前（任意回答）
- 職種（任意回答）｜フロントエンジニア、等

- 【TeckUp! LT大会】を何で知りましたか？
  - connpass
  - Twitter
  - 友人つながり
  - そのた（自由記入）

- 本イベントの満足度について教えてください
  - イベント全体の満足（とても満足・満足・普通・不満・とても不満）
  - LT発表の内容（とても満足・満足・普通・不満・とても不満）
  - LT発表の数（とても満足・満足・普通・不満・とても不満）
  - 休憩や交流の時間（とても満足・満足・普通・不満・とても不満）

- 「開催されれば参加したい」と思うイベント・企画等あればご記入ください

- 【TeckUp】主催イベントの運営に興味はありますか？（ある or ない）
  - 『ある』と答えた方｜連絡先をご記入ください（メールアドレス・Twitterアカウント等）

- 本日の感想や運営に期待すること等を自由にご記入ください
```

**Comment by IkezoeMakoto** [comment]
アンケートフォームあざます！

会場とかについての設問とか聞いたりしなくていいですかね？

（LTの内容や数はあまり運営でコントロール出来るところでもないので、コントロール出来るところの満足度がしりたいと思った）
