### ISSUE TITLE
当日の会場案内について

### ISSUE THREAD

**Issue by BBCapMegane** [teckup-tokyo/LT#87]
ref: #83 

- 入場案内は入館カードを持った運営がする
- 受付時間を過ぎた場合は、「#TeckUp」をつけて着いた旨ツイートしてもらい迎えにいく

確認事項
~~入館カードは貸出OK？ (社外の人間が会場案内できるのか？)~~

https://github.com/teckup-tokyo/LT/issues/87#issuecomment-504842890

**Comment by BBCapMegane** [comment]
> 入場案内のスタッフ、目印必要 ？

`こいつが案内します`　 的なツイートすればいいのでは？  服とか帽子の写真付きで

**Comment by nmeguro** [comment]
connpass にはこう書いときました。
>- 入場：スタッフが入場案内します。万が一スタッフが居ない場合は、正面入口付近でお待ちください。（休日のためビル入口は閉鎖されています）
>  - イベント開始後(13:30以降)に到着された場合はTwitterで、運営連絡先へ直接 or ハッシュタグ「#TeckUp」を付けて、到着した旨お知らせ下さい。

**Comment by nmeguro** [comment]
入館カードは（私のを含め）3枚確保する予定なので大丈夫です。

**Comment by nmeguro** [comment]
入口に立て看板を設置する予定なので、それの写真でもうｐすれば大丈夫かなと。

**Comment by nmeguro** [comment]
そう考えると案内する人2人欲しいなあ。
スタッフ誰もおらんやんけ！ ってならないようにしたいな、という気持ち。

**Comment by nmeguro** [comment]
connpassの文言、やっぱもう少しシンプルな文言にした。

> - 入場：スタッフが案内しますので、ビル正面入口付近までお越し下さい。（休日の為ビル入口は閉鎖されています）
>     - イベント開始後(13:30以降)に到着された場合は、Twitterで運営連絡先へ直接 or ハッシュタグ「#TeckUp」を付けて、到着した旨お知らせ下さい。

**Comment by BBCapMegane** [comment]
> そう考えると案内する人2人欲しいなあ。
> スタッフ誰もおらんやんけ！ ってならないようにしたいな、という気持ち。

**Comment by BBCapMegane** [comment]
> そう考えると案内する人2人欲しいなあ。
> スタッフ誰もおらんやんけ！ ってならないようにしたいな、という気持ち。

これ自分が受付兼、会場誘導すれば済みそうなのではと思うのですがどうでしょう？
(受付は、自分含めて2人いるので)

**Comment by nmeguro** [comment]
>これ自分が受付兼、会場誘導すれば済みそうなのではと思うのですがどうでしょう？

おお！ 良い良い！ ではそれで。

**Comment by BBCapMegane** [comment]
> connpassの文言、やっぱもう少しシンプルな文言にした。
> 
> > * 入場：スタッフが案内しますので、ビル正面入口付近までお越し下さい。（休日の為ビル入口は閉鎖されています）
> >   
> >   * イベント開始後(13:30以降)に到着された場合は、Twitterで運営連絡先へ直接 or ハッシュタグ「#TeckUp」を付けて、到着した旨お知らせ下さい。

伝われば良いと思いますし、別に変ではないのでこのままでいいと思いますよ！
(正直みんなちゃんと読まないし)
