### ISSUE TITLE
振り返りする

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/LT#89]
振り返りする

_Originally posted by @IkezoeMakoto in https://github.com/teckup-tokyo/LT/issues/80#issuecomment-510085658_

**Comment by IkezoeMakoto** [comment]
調整さん

https://chouseisan.com/s?h=156dbe2caf6a4b64bfdd2c717e87e0e6

**Comment by IkezoeMakoto** [comment]
振り返りは8/2

**Comment by IkezoeMakoto** [comment]
各自ここに振り返り内容書いておいてください

**Comment by yumechi** [comment]
# Y

* 開催できた
* オプトさんでイベントを借りてイベントできた（ありがとうございます）
* 参加者の伸びが悪かったため、ちょっと多めにリマインドした 

# W

* 案外Connpass経由で参加する人もいる
    * 今回参加してくれた学生さんとか
    * 大概的な告知はある程度の意味を持つ
* 3連休の初日だったこともあり、参加率が悪かった？
    * 他のイベントを見ていても、そんなことはないと思うが…
    * 少しこのあたりについてはLTしたい人と、LT聞きたい人のターゲット想定をもう少し明確にすべきかも
* 会場の場所につくまでに迷って遅刻した
    * すみません
* ノンアルコールだったけど、いい感じに盛り上がった
    * あるならあるでOK（他では日本酒LTとかもあるので、どうするのかは今後のイベントの方針次第）
* アンケート結果がよく、懇親会の参加者が非常に多かった
    * イベントの満足度に依存している？
    * もう少し分析したいところではある
    * 人の関る時間が増えるということはなにかが起こる可能性があるので、ポリシーを明確にしたほうがいいかも
* iPadの経過時間表示はとても良かった（これはにへーさんに感謝）
* イベント告知がギリギリすぎた感ある（一ヶ月前に予定を立てしまっている人も多いので、次回決まったらすぐ公開するくらいの勢いで行きたい）
* あくまで発表すること・挑戦してもらうことを主題にしたいので、表彰とかは今後も行わなくてもいいかなと思う。
    * 他のLTイベントに参加して感じたことだけど、経験してもらうことを主題に置きたい

# T

* ポリシー系の整備
    * 昨今はハラスメントなどの問題が起こりがちであり、それを事前に防ぐための活動を理解してやっています、というのを明確にしたい
* イベント公開はできたら公開 OR 1ヶ月半前に大きなイベントがないことを確認して公開
    * カンファレンスカレンダーとか大きめのイベントはちゃんとチェックすること
* タイムスケジュールの見直し
    * イベント自体が長すぎるのではないか、という気がしてきた。LT予定数を10本にして、残り飛び込みタイムを30分位でもよいのではないだろうか？
* テーマ選定の変更
    * 技術、は広すぎて話題探しに困ったのではと思う
    * 他のLTイベントのタイトルを借りてしまうかもしれないが、最近の失敗とか、最近始めた技術とか、そういうのも良さそう

**Comment by IkezoeMakoto** [comment]
一旦（あとで追加するかも）

## Y
* 日程決めから開催までの進捗管理をした
* PM的な役割を途中から責任持ってやった
  * イベントに必要なもの洗い出したり、担当割り振りしたり
* 担当が決まらなかったやつやった（落穂拾い)
  * 懇親会会場押さえとか
  * 事前告知とか
  * 貴族会のグループメッセージ送信とか
  * コンパスページの公開とか
* 貴族会SlackからTeckUpへ移行してもらうようにお願いした
  * これはyumechiさんと一緒にやった
* コミット履歴を改変した

## W
* PM的な役割がいないと、問題が起きたときに改善できない
  * 多分みんなが稼働に余裕があって、問題が起きていないときはうまくいくんだと思う
  * ので、PMを担当制にして回していくようにしたほうが良さそう
    * とはいえ、PMやりたいわけじゃないんだよなぁ、の人もいると思うし時期的に忙しいとかもあると思う
* git運用するならある程度、メンバーが使える状態じゃないと危険
  * いざというとき対応出来る人がいない
* イベント運営の立ち位置的な役割分担ができていなかったなぁ。
  * タスクに対する役割分担は主導してやっていたが、それぞれの人がどういう価値提供できるかを考えての役割分担ができていなかった
* LTしたい、って人をうまくターゲッティングできていない
  * これは命名なのか、なんなのかわからないが、ほぼ同じ日程でも集まってるイベントは集まってるのでイベント固有の問題なんだろう
  * とはいえ、最終的にはみんな頑張ってくれた結果か、それなりに盛り上がった

## T
* KickOff時にイベントのテーマ（目的と方向性）と推進者(PM的な役割)を決める
* 時期的に忙しくなさそうなタイミングを見てイベント企画する

**Comment by Ushinji** [comment]
## やったこと
- (今回は事前準備に関わっていないので、特になし)

## 気づいたこと、感じたこと
- LT会第一回が開催できた！
- オプトさんの会場という、新天地で開催できた！
- 参加者は少なかったけど、参加した人のモチベーションは高かったので、総じて発表内容は面白くて、勉強になったし、盛り上がったと思う
- 運営に関して、人数がそれなりにいると「自分がやらなければ！」という気持ちも生まれず、誰かがやってくれるだろうという気持ちになった
  - 自分はそう感じたし、結果的に自分は事前準備はほとんど関わらなかったです
  - なので、今回運営を率先してやって下さったみなさまに感謝🙇‍♂️
  - あと、関わり方って人それぞれ得意・不得意と思うので、事前に関わり方のすり合わせをしていればよかった

## 次にやること
- 事前に運営の中で、関わり方の立ち位置を話し合って、互いに認識を合わせておく

**Comment by nmeguro** [comment]
## Y - やったこと

### 前日まで
- 会場提供
- connpassページをちょっとだけ更新
- メール文章をちょっとだけ推敲

### 当日
- 会場設営（何人かで実施）
- 司会進行

## W - 分かったこと

### Good
- connpass経由の参加者が意外といる
  - もっと訴求していきたい。分析したい。
- アンケート回答率が良かった
  - 回答用の時間を設けることが肝要
- アンケートの結果も良かった
  - 忖度も含まれているのかしら？
- 会場設営＆撤収みんな手伝ってくれる
  - やさしい世界

### More
- タイムテーブル順守が大変
  - 今回は余裕もあったし、個人的にはライブ感はあって良いと思うが、参加者いっぱいだとどうだろう。
- 質問がその場になりがち
  - Twitterで質問が飛んでくると個人的に嬉しかった（後から拾えるので）
- 参加者が少なかった
  - 盛り上がったので良かったが、30人くらい来てくれると大変嬉しかった。
  - 3連休関係あるのかな。まぁ1回目だしこんなものか？
- やっぱりちょっと長い
  - TL10名で良いと思った
  - 10名以上LTしたい場合は増設すれば良い気がする
- アンケート結果に忖度は含まれていないか？
  - 設問は現状で良いのか、Good/Modeが分析出来るかは微妙な気がしている。
- ちょっと内輪っぽくなってなかったか？
  - 特に最後の飛び込みLTのあたりとか。

## T - 次やること

- テーマをちゃんと決める
  - せめて「フロントエンド」とかそういう粒度でも良いので。
- 会場で懇親会をやりたい
  - 居酒屋だとただの飲みになってしまうので
  - 飛び込みLTは懇親会で行いたい

**Comment by BBCapMegane** [comment]
# Y
- 開催できたこと
- オプトさんでの開催実績
- 会の宣伝した( Twitter、LTした後)
- compass page のレビューした
- LTした

# W
- 参加者は以外と集まらない
- 参加者の温度感は高いのでいい会だった(ただここらへんはかなり参加者に依存する)
-  当日の進行はゆるい感じでよかった
- 運営作業にちゃんとコミットできていなかった(zoeさんに頼りすぎ)

# T
- 次回LTの開催日 開催場所
- 次のリーダー スタッフ
- スタッフの役割の明確化
- 会場で懇親会したい

**Comment by DAdDY0055** [comment]
# Y
- 事前のconnpassページの作成　→　貴族会の流用であるが、次回以降使い回しできるはず　
- 当日の受付、あっきーとにへーさんが協力してスムーズにやってくれた
- 直前だったがそれなりに人が集まってくれた
- ほぼノンジャンルだが色々ばらけて面白かった

# W
- あらかじめ期限や役割を決めておかないと途中でバタつく
  - zoeさん頼みだったのは反省
- (参加者に聞いたところ)LTで縛りなく話したいという需要はそれなりにあるようだ
  - 自分のアプリやサービスの宣伝など
- とはいえテーマは日程などを決める際、あらかじめ決めておきたい
- 1ヶ月あると担当の人が急遽忙しくなってできなくなることがあると思うのでフォロー体制についても決めておいても良いかも(やりすぎ？)

# T
- テーマの決定方法を考える(皆集まった時、GitHubの投票でなど)
- LTの枠数、時間、タイムスケジュール
- 役割(事前に何をする人が必要か)の洗い出し

**Comment by yutonihei** [comment]
## Y - やった事
### 前日まで
 - 何もしていない（できなかったのは反省点）
### 当日
 - 会場設営、音響準備
 - 会場案内
## W - わかった事
 - 三連休だったためか、伸び率があまり良くはなかった（人数的には程よい感じだったがと思うが）
 - Connpass経由の人が意外といてびっくり
 - タイムスケジュールの管理が難しく、懇親会と打ち上げの間がそこそこ空いて微妙な間ができてたとおもう、要調整
 - テーマがフリー故の自由さがあることを再認識できた
 - 当日やったLTを振り返りできるようにどこかで共有しておきたい気がした
## T - 次やる事
 - 今回タスクとしてやらなかった事（Connpass編集や告知準備などのタスク）をやっていきたい
 - ジョブローテーションじゃないけど、役割を決めて順番に回してスキルを伸ばしていければいいのかな...？（得手不得手があると思うので難しいところだけど）

**Comment by IkezoeMakoto** [comment]
▼決まったこと
次回リーダー： あっきー
次回開催予定：11/9, 11/10あたり
キックオフ：10月頭くらい(10/9,10/10をコンパス公開目安にするため)
会場候補：Pi○iv行きたい

**Comment by IkezoeMakoto** [comment]
振り返った！！！
