### ISSUE TITLE
[第5回] 懇親会の料理 お酒

### ISSUE THREAD

**Issue by BBCapMegane** [teckup-tokyo/LT#99]
懇親会の料理 お酒 について

**Comment by yutonihei** [comment]
予算は現状人数×500＋αで11000円
以下Slackからのコピー
```
フード4750円（フィンガーフードOnly、未選定）
ドリンク代5750円（缶チューハイ30缶@110円、缶ビール10缶@200円、ソフドリPET3本@150円）
雑費500円（コップとウエットティッシュ、箸・皿は未考慮）
```
上記の条件でフードを探しているけどシェフコレでは条件に合致するものがない（最小660円×15人=9900円）
他に良い情報があったら共有まってます

**Comment by BBCapMegane** [comment]
https://demae-can.com/search/delivery/13113017004/?zip=1510051&orderTyp=0
出前館どうよ！

**Comment by yutonihei** [comment]
出前館悪くなさそうではあるけど何をチョイスするか悩んでしまった・・・笑
片道10分にピザハット代々木店があるのは確認したので、
終了近くに私が取りに行ってこようかなー感はある
あと常温で置いておいても美味しく食べれそう（だけど若干準備が必要）
なのはミスドのドーナツ1000円分くらいを1/6くらいにカットして、
つまようじ刺しておけば食べやすいかなーとか思ったり

一応ここでの報告になるけど、以下のものは購入したので持っていきます！
・紙コップ 275ml 30個
・紙皿 18cm 25枚
・ウェットティッシュ 70枚入
・ゴミ袋 50L 24枚
上記4点110円×4点=440円です。

**Comment by BBCapMegane** [comment]
買い出しありがとうございます！
かかったお金は後で割るので、ざっくりどこかに記録してもらえるとありがたいです

**Comment by yutonihei** [comment]
Slackに書いた案をこっちにも
バリエーション考えるの大変だったので、
・持ち帰りピザMサイズ3枚 3024円
・ミスドのドーナツ1000円分位（を後で6等分とか）
・残り700円位はコンビニお菓子
はどうでしょうか！

**Comment by yutonihei** [comment]
> 買い出しありがとうございます！
> かかったお金は後で割るので、ざっくりどこかに記録してもらえるとありがたいです

編集して追記しておきましたー！

**Comment by yutonihei** [comment]
ドーナツポップS（8個入り）270円
ドーナツポップL（24個入り）760円
合計1030円でした。

**Comment by yutonihei** [comment]
ドリンク代、税別価格の場所で購入したのでちょっとオーバーして６３２２円でした。。

**Comment by yutonihei** [comment]
ピザ（ドミノ・ピザ）
クワトロハッピー１
クワトロハッピー２
２枚以上50% Off
で合計2751円でした。
別途あっきーに買ってもらったお菓子代がいくらか分からなくなっちゃったみたいですが500円を計上しておきます。
また、会場参加のtadsanさんからお菓子をいくらから提供いただきましたので報告です。

**Comment by yutonihei** [comment]
費用徴収
500円×15人=7500円
ピザ2751円
ドーナッツ1030円
ドリンク代6322円
その他お菓子代500円
雑費代440円
費用合計10543円

残ったやつ
ドリンク：10本×110円+120円=1220円
雑費（ゴミ袋）：110円
合計1330円

計：9213円

なので1713円の赤字です。

**Comment by yutonihei** [comment]
残ったやつを考慮しない場合は10543-7500=3043円の赤字です。
なので6人で一人500円ですね。
